### ISSUE TITLE
Cannot call method 'fingerprint', of unidentified

### ISSUE THREAD

**Issue by venkat** [keybase/keybase-issues#1349]
keybase encrypt -s -m "hi" venkat
warn: No config file found; tried '/Users/venkat/.config/keybase/config.json'
...
/usr/local/lib/node_modules/keybase/lib/command/encrypt.js:89
        args.push("--sign", "-u", sign_key.fingerprint(true));
                                           ^
TypeError: Cannot call method 'fingerprint' of undefined
    at Command.exports.Command.Command.do_encrypt (/usr/local/lib/node_modules/keybase/lib/command/encrypt.js:89:44)
    at /usr/local/lib/node_modules/keybase/lib/command/encrypt.js:237:21
    at /usr/local/lib/node_modules/keybase/lib/command/encrypt.js:241:15
    at iced.Deferrals.parent (/usr/local/lib/node_modules/keybase/lib/command/encrypt.js:227:24)
    at Deferrals.exports.Deferrals.Deferrals._call (/usr/local/lib/node_modules/keybase/node_modules/iced-runtime/lib/runtime.js:86:16)
    at /usr/local/lib/node_modules/keybase/node_modules/iced-runtime/lib/runtime.js:98:26
    at exports.trampoline.trampoline (/usr/local/lib/node_modules/keybase/node_modules/iced-runtime/lib/runtime.js:64:14)
    at Deferrals.exports.Deferrals.Deferrals._fulfill (/usr/local/lib/node_modules/keybase/node_modules/iced-runtime/lib/runtime.js:96:16)
    at ret (/usr/local/lib/node_modules/keybase/node_modules/iced-runtime/lib/runtime.js:29:18)
    at /usr/local/lib/node_modules/keybase/node_modules/iced-error/index.js:92:22

**Comment by waldyrious** [comment]
Possibly related: #41

Also, there's a typo in this issue's title: "unidentified" instead of "undefined".
