### ISSUE TITLE
keybase login fails on Windows with TypeError: Request path conatins unescaped characters

### ISSUE THREAD

**Issue by guerda** [keybase/keybase-issues#1397]
```
> keybase login
warn: No config file found; tried 'C:\Users\XXXX\AppData\Roaming\keybase\config.json'
Your keybase username or email: XXXXX
Your keybase login passphrase: XXXXX
_http_client.js:73
    throw new TypeError('Request path contains unescaped characters.');
          ^
TypeError: Request path contains unescaped characters.
    at new ClientRequest (_http_client.js:73:11)
    at TunnelingAgent.exports.request (http.js:49:10)
    at TunnelingAgent.createSocket (C:\Users\XXXXX\AppData\Roaming\npm\node_modules\keybase\node_modules\request\node_modules\tunnel-agent\index.js:117:25)
    at TunnelingAgent.createSecureSocket [as createSocket] (C:\Users\XXXXX\AppData\Roaming\npm\node_modules\keybase\node_modules\request\node_modules\tunnel-agent\index.js:184:41)
    at TunnelingAgent.addRequest (C:\Users\XXXXX\AppData\Roaming\npm\node_modules\keybase\node_modules\request\node_modules\tunnel-agent\index.js:80:8)
    at new ClientRequest (_http_client.js:154:16)
    at Object.exports.request (http.js:49:10)
    at Object.exports.request (https.js:136:15)
    at Request.start (C:\Users\XXXXX\AppData\Roaming\npm\node_modules\keybase\node_modules\request\request.js:583:30)
    at Request.end (C:\Users\XXXXX\AppData\Roaming\npm\node_modules\keybase\node_modules\request\request.js:1237:28)
```

Windows 7 x64
I sit behind a proxy, but exported the settings into environment variables. Installation worked pretty well with this.

**Comment by thom-leggett** [comment]
This also happens on linux when behind a http proxy. Without the proxy the client works fine.

**Comment by robreardon** [comment]
I'm behind a proxy too but I've managed to get this working.

I modified package.json under node_modules\keybase, and changed "request": "2.30.0" to "request": "2.51.0", and then ran "npm update request".
