### ISSUE TITLE
TypeError: Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by bronwynlewis** [keybase/keybase-issues#1398]
Upgrading to the latest keybase just now, I got this error when I tried to track another user and when I tried to look at my own ID verification (which works fine for other folks).

```
➜  ~  keybase id bronwyn
/usr/local/lib/node_modules/keybase/lib/sigchain.js:516
              _results.push(email.toLowerCase());
                                 ^
TypeError: Cannot read property 'toLowerCase' of undefined
    at /usr/local/lib/node_modules/keybase/lib/sigchain.js:516:34
    at /usr/local/lib/node_modules/keybase/lib/sigchain.js:519:13
    at Deferrals.exports.Deferrals.Deferrals._call (/usr/local/lib/node_modules/keybase/node_modules/iced-runtime/lib/runtime.js:86:16)
    at /usr/local/lib/node_modules/keybase/node_modules/iced-runtime/lib/runtime.js:98:26
    at exports.trampoline.trampoline (/usr/local/lib/node_modules/keybase/node_modules/iced-runtime/lib/runtime.js:64:14)
    at Deferrals.exports.Deferrals.Deferrals._fulfill (/usr/local/lib/node_modules/keybase/node_modules/iced-runtime/lib/runtime.js:96:16)
    at ret (/usr/local/lib/node_modules/keybase/node_modules/iced-runtime/lib/runtime.js:29:18)
    at /usr/local/lib/node_modules/keybase/node_modules/iced-error/index.js:92:22
    at /usr/local/lib/node_modules/keybase/node_modules/gpg-wrapper/lib/keyring.js:549:18
    at /usr/local/lib/node_modules/keybase/node_modules/gpg-wrapper/lib/keyring.js:541:22
```

The one thing I suspect might be contributing to this is that I don't have an email address under my main identity.

**Comment by maxtaco** [comment]
yeah

will fix shortly. thx for bug report

**Comment by maxtaco** [comment]
Bugfix live in v0.7.7

**Comment by bronwynlewis** [comment]
Works for me - thanks!
