### ISSUE TITLE
Bad temp directory detection

### ISSUE THREAD

**Issue by kenzierocks** [keybase/keybase-issues#1439]
On powershell (posh), tried running `keybase-installer` but it failed, telling me that the `TEMP` environment variable didn't end in `\Temp`. I `echo`'d it, and sure enough, it doesn't end in `\Temp` but in `\Temp\`. Could this be fixed to detect trailing slashes?

Log:
```
info: Made temporary directory: C:\Users\Kenzie Togami\AppData\Local\Temp\keybase_install_xMb98lsDmbfZ1NQhKOen7w
C:\Users\Kenzie Togami\AppData\Roaming\npm\node_modules\keybase-installer\node_modules\keybase-path\lib\main.js:232
          throw err;
                ^
Error: TEMP didn't end in \Temp
    at Win32.home (C:\Users\Kenzie Togami\AppData\Roaming\npm\node_modules\keybase-installer\node_modules\keybase-path\lib\main.js:230:203)
    at home (C:\Users\Kenzie Togami\AppData\Roaming\npm\node_modules\keybase-installer\lib\config.js:65:15)
    at Config.exports.Config.Config.get_keyring_dir (C:\Users\Kenzie Togami\AppData\Roaming\npm\node_modules\keybase-installer\lib\config.js:86:16)
    at Config.exports.Config.Config.init_keyring (C:\Users\Kenzie Togami\AppData\Roaming\npm\node_modules\keybase-installer\lib\config.js:113:18)
    at iced.Deferrals.parent (C:\Users\Kenzie Togami\AppData\Roaming\npm\node_modules\keybase-installer\lib\installer.js:326:36)
    at C:\Users\Kenzie Togami\AppData\Roaming\npm\node_modules\keybase-installer\lib\installer.js:330:23
    at Deferrals.exports.Deferrals.Deferrals._call (C:\Users\Kenzie Togami\AppData\Roaming\npm\node_modules\keybase-installer\node_modules\iced-runtime\lib\runtime.js:86:16)
    at C:\Users\Kenzie Togami\AppData\Roaming\npm\node_modules\keybase-installer\node_modules\iced-runtime\lib\runtime.js:98:26
    at exports.trampoline.trampoline (C:\Users\Kenzie Togami\AppData\Roaming\npm\node_modules\keybase-installer\node_modules\iced-runtime\lib\runtime.js:64:14)
    at Deferrals.exports.Deferrals.Deferrals._fulfill (C:\Users\Kenzie Togami\AppData\Roaming\npm\node_modules\keybase-installer\node_modules\iced-runtime\lib\runtime.js:96:16)
```
Environment variables relevant:
`TEMP`: `C:\Users\Kenzie Togami\App Data\Local\Temp\`

**Comment by kouk** [comment]
:+1: 
I have this problem too. Unfortunately, in the related Windows env vars dialog, the environment variable doesn't have the trailing slash, but in Powershell it does. So even if I wanted to I do not know how to change this, and am too bored to find a way to do it since I can just do `$env:Temp="$env:localappdata\Temp"` manually instead before running keybase.

**Comment by cmol** [comment]
@kouk, how exactly did you solve this? I tried some different stuff, but windows isn't really my strong side.

**Comment by kenzierocks** [comment]
@cmol You need to be in PowerShell to do what __kouk__ did, just run the code in the code block in posh with the correct temp directory. `$env:TEMP="<directory>"`

**Comment by oconnor663** [comment]
Ok, I think we fixed this issue in https://github.com/keybase/node-path/commits/master, but `keybase-installer` did not include that fix. I just pushed version 1.0.3 that should include it. @kenzierocks can you confirm this works for you?

**Comment by kenzierocks** [comment]
Yes, this works fine. Thanks!

**Comment by oconnor663** [comment]
Sweet.
