### ISSUE TITLE
crash in command line tool

### ISSUE THREAD

**Issue by nickdesaulniers** [keybase/keybase-issues#1526]
```
➜  ~  keybase signup
warn: No config file found; tried '/Users/Nicholas/.config/keybase/config.json'
Your email: <I've removed this>
Invitation code (leave blank if you don't have one): <I've removed this>
Your desired username: nick
Your login passphrase: <I've removed this>
Your login passphrase (must be at least 12 letters long): <I've removed this>
Repeat to confirm: <I've removed this>
- run scrypt [==================================] 100%
error: Username 'nick' already registered
Your email: ndesaulniers@mozilla.com
Invitation code (leave blank if you don't have one): <I've removed this>
Your desired username: nickd
Your login passphrase: (<default hidden>)
_http_outgoing.js:333
    throw new Error('"name" and "value" are required for setHeader().');
          ^
Error: "name" and "value" are required for setHeader().
    at ClientRequest.OutgoingMessage.setHeader (_http_outgoing.js:333:11)
    at new ClientRequest (_http_client.js:101:14)
    at Object.exports.request (http.js:49:10)
    at Object.exports.request (https.js:136:15)
    at Request.start (/Users/Nicholas/.nvm/versions/node/v0.12.0/lib/node_modules/keybase/node_modules/request/request.js:583:30)
    at Request.write (/Users/Nicholas/.nvm/versions/node/v0.12.0/lib/node_modules/keybase/node_modules/request/request.js:1232:28)
    at /Users/Nicholas/.nvm/versions/node/v0.12.0/lib/node_modules/keybase/node_modules/request/request.js:403:14
    at process._tickCallback (node.js:355:11)
```

**Comment by maxtaco** [comment]
Thanks for the bug report, have never seen this one before.  Can you provide `keybase signup -d` logging output? Please make sure to redact your passphrase and invite code as before.  Many thanks!

**Comment by nickdesaulniers** [comment]
```
➜  bubble_game git:(master) ✗ keybase signup -d
usage: keybase join [-h]
keybase join: error: Unrecognized arguments: -d.
```

**Comment by maxtaco** [comment]
Sorry, I meant `keybase -d signup`.

**Comment by nickdesaulniers** [comment]
```
➜  bubble_game git:(master) ✗ keybase -d signup
debug: + opening config file: /Users/Nicholas/.config/keybase/config.json
debug: ++ loading config file /Users/Nicholas/.config/keybase/config.json
debug: -- loaded config file -> {"user":{"email":"ndesaulniers@mozilla.com","salt":"<I have removed this>","name":"nickd","id":"<I have removed this>"}}
debug: - opened config file; found=true
debug: + testing GPG command-line client <default: gpg2 or gpg>
debug: | using GPG command: gpg
debug: - tested GPG command-line client -> null
debug: Setting GPG_TTY=/dev/ttys039
debug: + Load proxy CAs
debug: - Loaded proxy CAs
debug: + startup message
debug: | CLI version: 0.7.7
debug: | Platform info: {"versions":{"http_parser":"2.3","node":"0.12.0","v8":"3.28.73","uv":"1.0.2","zlib":"1.2.8","modules":"14","openssl":"1.0.1l"},"arch":"x64","platform":"darwin","features":{"debug":false,"uv":true,"ipv6":true,"tls_npn":true,"tls_sni":true,"tls_ocsp":true,"tls":true}}
debug: | Version info: ["keybase (keybase.io CLI) v0.7.7","- node.js v0.12.0","- gpg (GnuPG) 1.4.19","- Copyright (C) 2015 Free Software Foundation, Inc.","Identifies as: 'keybase.io node.js client v0.7.7 darwin'"]
debug: - startup message
debug: + opening database file: /Users/Nicholas/.local/share/keybase/keybase.idb
debug: ++ DB::_init_db
debug: -- DB::_init_db -> 0
debug: - DB opened
debug: + session::load
debug: ++ opening config file: /Users/Nicholas/.cache/keybase/session.json
debug: +++ loading config file /Users/Nicholas/.cache/keybase/session.json
debug: --- loaded config file -> <redacted>
debug: -- opened config file; found=true
debug: - session::load
Already registered; do you want to reregister? [y/N] n
error: registration canceled
```

**Comment by maxtaco** [comment]
Thank you!
