### ISSUE TITLE
Attempt to allocate Buffer larger than maximum size

### ISSUE THREAD

**Issue by xcoderzach** [keybase/keybase-issues#1547]
I'm getting the error: 

```
RangeError: Attempt to allocate Buffer larger than maximum size: 0x3fffffff bytes
    at new Buffer (buffer.js:71:11)
    at Function.Buffer.concat (buffer.js:211:16)
    at BufferOutStream.exports.BufferOutStream.BufferOutStream.data (/usr/local/lib/node_modules/keybase/node_modules/iced-spawn/lib/stream.js:102:21)
    at /usr/local/lib/node_modules/keybase/node_modules/iced-spawn/lib/cmd.js:484:32
    at Deferrals.exports.Deferrals.Deferrals._call (/usr/local/lib/node_modules/keybase/node_modules/iced-runtime/lib/runtime.js:86:16)
    at /usr/local/lib/node_modules/keybase/node_modules/iced-runtime/lib/runtime.js:98:26
    at exports.trampoline.trampoline (/usr/local/lib/node_modules/keybase/node_modules/iced-runtime/lib/runtime.js:64:14)
    at Deferrals.exports.Deferrals.Deferrals._fulfill (/usr/local/lib/node_modules/keybase/node_modules/iced-runtime/lib/runtime.js:96:16)
    at ret (/usr/local/lib/node_modules/keybase/node_modules/iced-runtime/lib/runtime.js:29:18)
    at SpawnEngine.BaseEngine._maybe_call_callback (/usr/local/lib/node_modules/keybase/node_modules/iced-spawn/lib/cmd.js:57:16)
```

**Comment by maxtaco** [comment]
weird, i've never seen this one before. what's the context?

**Comment by xcoderzach** [comment]
We were trying to securely send a large ~6gb text file.  So we `keybase encrypt`ed it, sent it over airdrop, and `keybase decrypt`ed it, which is when I got this error.

**Comment by xcoderzach** [comment]
Is it weird that 6gb plaintext becomes only 950mb encrypted?

**Comment by maxtaco** [comment]
PGP has compression in the spec. It's a little bit of everything.  Sorry I didn't see your mention of a 950mb file.  Unfortunately we haven't gotten streaming to work yet in our library.  Grrr, we had a branch but had to switch onto something else.  You could use `gpg --decrypt` just for now.  Sorry about that.

**Comment by xcoderzach** [comment]
Good to know, and thanks for the great product!
