### ISSUE TITLE
Allow piping of sign/encrypt output

### ISSUE THREAD

**Issue by kfwls** [keybase/keybase-issues#1556]
Rather than having to specify a file with -o, or console grabbing the output with all the GPG junk, add an option to only output the resulting PGP block - so it can be piped into another process.

eg. To sign a message copied into clipboard, to paste back into a web client:
```
keybase sign -m Get-Clipboard --clean | Set-Clipboard
```

**Comment by zQueal** [comment]
Tried to do this now, but Keybase doesn't seem to like to play with stream operators.

```
λ keybase sign -m | pclip
This is a test
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: This socket is closed.
    at Socket._writeGeneric (net.js:656:19)
    at Socket._write (net.js:709:8)
    at doWrite (_stream_writable.js:301:12)
    at writeOrBuffer (_stream_writable.js:288:5)
    at Socket.Writable.write (_stream_writable.js:217:11)
    at Socket.write (net.js:634:40)
    at ArgumentParser._printMessage (C:\Users\zqueal\AppData\Roaming\npm\node_modules\keybase\node_modules\argparse\lib\argument_parser.js:1107:12)
    at ArgumentParser.printUsage (C:\Users\zqueal\AppData\Roaming\npm\node_modules\keybase\node_modules\argparse\lib\argument_parser.js:1086:8)
    at ArgumentParser.error (C:\Users\zqueal\AppData\Roaming\npm\node_modules\keybase\node_modules\argparse\lib\argument_parser.js:1162:8)
    at ArgumentParser.parseKnownArgs (C:\Users\zqueal\AppData\Roaming\npm\node_modules\keybase\node_modules\argparse\lib\argument_parser.js:294:10)
```

**Comment by lucaswerkmeister** [comment]
Works for me:
```shell
$ keybase sign -m $'Hello World!\n' | xclip; xclip -o | gpg
Hello World!
gpg: Signature made Mo 18 Mai 2015 18:30:40 CEST using RSA key ID 72AE323F
# […]
$ keybase sign -m $'Hello World!\n' | keybase verify
info: Valid signature from you
info: Signed less than a minute ago (5/18/2015, 6:31:06 PM)
$ uname
Linux
$ keybase --version
0.7.8
```

**Comment by kfwls** [comment]
Working here now too (under powershell). Odd.

**Comment by dtiersch** [comment]
@lucaswerkmeister @kfwls do you have a passphrase on your GPG-key?

**Comment by lucaswerkmeister** [comment]
yes, but my GPG agent seems to be working correctly: The first time I run the command, I get a `pinentry` prompt asking for my key; on subsequent executions, I don’t have to do anything.

**Comment by kfwls** [comment]
Yes, just checked, and it still works even without the passcode cached. Prompts for it as normal, then pipes the result.
