### ISSUE TITLE
Error and stack trace on `keybase prove twitter`

### ISSUE THREAD

**Issue by zetlen** [keybase/keybase-issues#1690]
On OSX 10.10, with (as the stacktrace shows) node installed via nvm, if that makes a difference.

```
09:13 $ keybase prove twitter
Your username on Twitter: jzetlen
/Users/james_zetlen/.nvm/versions/node/v0.12.5/lib/node_modules/keybase/lib/command/prove.js:578
                              _this.gen.run(esc(__iced_deferrals.defer({
                                       ^
TypeError: Cannot read property 'run' of null
    at iced.Deferrals.parent (/Users/james_zetlen/.nvm/versions/node/v0.12.5/lib/node_modules/keybase/lib/command/prove.js:578:40)
    at /Users/james_zetlen/.nvm/versions/node/v0.12.5/lib/node_modules/keybase/lib/command/prove.js:582:31
    at Deferrals.exports.Deferrals.Deferrals._call (/Users/james_zetlen/.nvm/versions/node/v0.12.5/lib/node_modules/keybase/node_modules/iced-runtime/lib/runtime.js:86:16)
    at /Users/james_zetlen/.nvm/versions/node/v0.12.5/lib/node_modules/keybase/node_modules/iced-runtime/lib/runtime.js:98:26
    at exports.trampoline.trampoline (/Users/james_zetlen/.nvm/versions/node/v0.12.5/lib/node_modules/keybase/node_modules/iced-runtime/lib/runtime.js:64:14)
    at Deferrals.exports.Deferrals.Deferrals._fulfill (/Users/james_zetlen/.nvm/versions/node/v0.12.5/lib/node_modules/keybase/node_modules/iced-runtime/lib/runtime.js:96:16)
    at ret (/Users/james_zetlen/.nvm/versions/node/v0.12.5/lib/node_modules/keybase/node_modules/iced-runtime/lib/runtime.js:29:18)
    at /Users/james_zetlen/.nvm/versions/node/v0.12.5/lib/node_modules/keybase/node_modules/iced-error/index.js:92:22
    at /Users/james_zetlen/.nvm/versions/node/v0.12.5/lib/node_modules/keybase/lib/command/proof_base.js:178:18
    at Deferrals.exports.Deferrals.Deferrals._call (/Users/james_zetlen/.nvm/versions/node/v0.12.5/lib/node_modules/keybase/node_modules/iced-runtime/lib/runtime.js:86:16)
```

**Comment by maxtaco** [comment]
Thanks.  This is a new one.  Can you paste the results of running the same command with the `-d` flag?

`keybase -d prove twitter`

it will output a lot of debug info, all of which is public.  anything private is redacted.

**Comment by zetlen** [comment]
Honestly this may be because my local config still doesn't think I have a key.

I had a lot of trouble getting my public key to pull. I generated it on the website, and then I could not pull it with the command line client after login.
```
09:03 $ keybase login
warn: No config file found; tried '/Users/james_zetlen/.config/keybase/config.json'
Your keybase username or email: zetlen
Your keybase login passphrase: **************************************
- run scrypt [==================================] 100%
info: Made directory '/Users/james_zetlen/.cache/keybase'
info: Updated file: /Users/james_zetlen/.cache/keybase/session.json
info: Made directory '/Users/james_zetlen/.config/keybase'
info: Updated file: /Users/james_zetlen/.config/keybase/config.json
error: you don't have a public key; try `keybase push` if you have a key; or `keybase gen` if you don't
```
Both `pull` and `push` resulted in the same error. I tried `gen`:
```
Generating keys...... Done!
Push your public key to the server? [Y/n] Y
Push your encrypted private key to the server? [Y/n] Y
error: You need to delete your active key before uploading a new one (error #908)
```
So I revoked the key I generated on the website. The website profile page again identified me as "a mystery user with no key". I ran `gen` again:

```
Generating keys.... Done!
Push your public key to the server? [Y/n] Y
Push your encrypted private key to the server? [Y/n] Y
info: success!
```

Immediately afterward I ran `prove twitter` and got the error I posted above.

After getting that error, I tried `pull` again and got the same `error: you don't have a public key`.

I tried `push`:
Multiple keys found, please pick one:
 (1)  4096R  (redacted)  exp: 2025-7-16  zetlen@keybase.io
 (2)  4096R  (redacted)  exp: 2025-7-16  zetlen@keybase.io
Pick a key: 1
info: Picked key: (redacted)
info: success!
```

Then I ran `pull` again:
`error: you don't have a public key; try `keybase push` if you have a key; or `keybase gen` if you don't`

So this issue may be a case of bad faulting when you still don't have a key, and the underlying issue is that I still can't get my public key to work locally. I will, however, post a debug log right now.

**Comment by maxtaco** [comment]
I think you're right.  @oconnor663 is working on this issue.  It's a recently-introduced bug.  It'll hopefully be fixed soon. Thanks for your patience.

**Comment by zetlen** [comment]
No problem. Thank you for your prompt response. Here's my debug log, though I did redact anything in hex--I realize it's supposed to all be public keys or meaningless salts, but given the state of the tool I didn't want to trust the debugging output too far.

```
09:23 $ keybase -d prove twitter
debug: + opening config file: /Users/james_zetlen/.config/keybase/config.json
debug: ++ loading config file /Users/james_zetlen/.config/keybase/config.json
debug: -- loaded config file -> {"user":{"name":"zetlen","salt":"[redacted]","id":"28c[redacted]"}}
debug: - opened config file; found=true
debug: + testing GPG command-line client <default: gpg2 or gpg>
debug: | using GPG command: gpg
debug: - tested GPG command-line client -> null
debug: Setting GPG_TTY=/dev/ttys004
debug: + Load proxy CAs
debug: - Loaded proxy CAs
debug: + startup message
debug: | CLI version: 0.8.10
debug: | Platform info: {"versions":{"http_parser":"2.3","node":"0.12.5","v8":"3.28.71.19","uv":"1.6.1","zlib":"1.2.8","modules":"14","openssl":"1.0.1o"},"arch":"x64","platform":"darwin","features":{"debug":false,"uv":true,"ipv6":true,"tls_npn":true,"tls_sni":true,"tls_ocsp":true,"tls":true}}
debug: | Version info: ["keybase (keybase.io CLI) v0.8.10","- node.js v0.12.5","- gpg (GnuPG/MacGPG2) 2.0.27","- libgcrypt 1.6.3","Identifies as: 'keybase.io node.js client v0.8.10 darwin'"]
debug: - startup message
debug: + opening database file: /Users/james_zetlen/.local/share/keybase/keybase.idb
debug: ++ DB::_init_db
debug: -- DB::_init_db -> 0
debug: - DB opened
debug: + session::load
debug: ++ opening config file: /Users/james_zetlen/.cache/keybase/session.json
debug: +++ loading config file /Users/james_zetlen/.cache/keybase/session.json
debug: --- loaded config file -> <redacted>
debug: -- opened config file; found=true
debug: - session::load
debug: + session::check
debug: | calling to sesscheck
debug: ++ request to sesscheck (https://api.keybase.io:443/_/api/1.0/sesscheck.json) (cookie=true)
debug: || Adding a custom CA for host api.keybase.io when tls=true
debug: -- request to sesscheck -> null
debug: - session::check
debug: + User::load_me
debug: ++ zetlen: load user
debug: +++ zetlen: load user from local storage
debug: ++++ load sig chain from local storage
debug: |||| No payload hash tail pointer found
debug: ---- loaded sig chain from local storage
debug: --- zetlen: loaded user from local storage -> null / [object Object]
debug: || Checking session since we're loading User as self (and need secret key)
debug: +++ session::load_and_check
debug: ++++ session::check
debug: |||| calling to sesscheck
debug: +++++ request to sesscheck (https://api.keybase.io:443/_/api/1.0/sesscheck.json) (cookie=true)
debug: ||||| Adding a custom CA for host api.keybase.io when tls=true
debug: ----- request to sesscheck -> null
debug: ---- session::check
debug: --- session::load_and_check -> true
debug: +++ zetlen: load user from server
debug: ++++ merkle find_and_verify: uid undefined, username zetlen
debug: +++++ request to merkle/path (https://api.keybase.io:443/_/api/1.0/merkle/path.json?uid=&username=zetlen) (cookie=true)
debug: ||||| Adding a custom CA for host api.keybase.io when tls=true
debug: ----- request to merkle/path -> null
debug: +++++ merkle get_merkle_pgp_key
debug: ||||| Call to gpg: { args: [ '-k', '--with-fingerprint', '--with-colons' ],
debug:   quiet: true,
debug:   no_options: true }
debug: ||||| merkle key already found in keyring
debug: ----- merkle get_merkle_pgp_key
debug: |||| Load key /2A3[redacted] from master keyring (secret=undefined)
debug: |||| Call to gpg: { args: 
debug:    [ '--export',
debug:      '--export-options',
debug:      'export-local-sigs',
debug:      '-a',
debug:      '2A3[redacted]' ] }
debug: +++++ lookup UID
debug: ++++++ read_uids_from_keys 03E[redacted]
debug: |||||| Call to gpg: { args: 
debug:    [ '-k',
debug:      '--with-fingerprint',
debug:      '--with-colons',
debug:      '03E[redacted]' ],
debug:   quiet: true,
debug:   no_options: true }
debug: |||||| got: [{"username":"Keybase.io Merkle Signing","comment":"v1","email":"merkle@keybase.io"}]
debug: ------ read_uids_from_key -> null
debug:  - Map 2A3[redacted] -> [object Object] via gpg
debug: ----- looked up UID
debug: +++++ Rollback check
debug: ||||| DB put value kv:e2:c5e[redacted]
debug: ||||| DB put lookup: lo:5:latest -> 4ba[redacted]
debug: ----- Rollback check
debug: |||| id_version (4) and seqno (undefined) haven't changed.
debug: +++++ zetlen: verifying signatures
debug: ----- zetlen: verified signatures
debug: +++++ zetlen: storing signature chain
debug: ----- zetlen: stored signature chain
debug: ---- zetlen: loaded user
debug: --- User::load_me
Your username on Twitter: jzetlen
debug: +++ check_exists_2
debug: ||| Remote proofs: null
debug: ||| Service name: twitter
debug: ||| Remote_name_normalized: jzetlen
debug: --- check_exists_2
debug: +++ load public key for zetlen
debug: ||| Load key zetlen/ from master keyring (secret=undefined)
debug: ||| Call to gpg: { args: 
debug:    [ '--export',
debug:      '--export-options',
debug:      'export-local-sigs',
debug:      '-a',
debug:      'zetlen' ] }
debug: ++++ lookup fingerprint
debug: |||| Call to gpg: { args: [ '-k', '--fingerprint', '--with-colons', 'zetlen' ],
debug:   no_options: true }
debug: +++++ lookup UID
debug: ++++++ read_uids_from_keys undefined
debug: |||||| Call to gpg: { args: [ '-k', '--with-fingerprint', '--with-colons' ],
debug:   quiet: true,
debug:   no_options: true }
debug: |||||| got: [{"username":"GPGTools Team","email":"team@gpgtools.org"},{"username":"GPGMail Project Team","comment":"Official OpenPGP Key","email":"gpgmail-devel@lists.gpgmail.org"},{"username":"GPGTools Project Team","comment":"Official OpenPGP Key","email":"gpgtools-org@lists.gpgtools.org"}]
debug: ------ read_uids_from_key -> null
debug: ||||| got back more than one UID; using the first: ([{"username":"GPGTools Team","email":"team@gpgtools.org"},{"username":"GPGMail Project Team","comment":"Official OpenPGP Key","email":"gpgmail-devel@lists.gpgmail.org"},{"username":"GPGTools Project Team","comment":"Official OpenPGP Key","email":"gpgtools-org@lists.gpgtools.org"}])
debug:  - Map zetlen -> [object Object] via gpg
debug: ----- looked up UID
debug: ---- load public key; found=true; err=GpgError: Found more than one (#l) keys for zetlen
/Users/james_zetlen/.nvm/versions/node/v0.12.5/lib/node_modules/keybase/lib/command/prove.js:578
                              _this.gen.run(esc(__iced_deferrals.defer({
                                       ^
TypeError: Cannot read property 'run' of null
    at iced.Deferrals.parent (/Users/james_zetlen/.nvm/versions/node/v0.12.5/lib/node_modules/keybase/lib/command/prove.js:578:40)
    at /Users/james_zetlen/.nvm/versions/node/v0.12.5/lib/node_modules/keybase/lib/command/prove.js:582:31
    at Deferrals.exports.Deferrals.Deferrals._call (/Users/james_zetlen/.nvm/versions/node/v0.12.5/lib/node_modules/keybase/node_modules/iced-runtime/lib/runtime.js:86:16)
    at /Users/james_zetlen/.nvm/versions/node/v0.12.5/lib/node_modules/keybase/node_modules/iced-runtime/lib/runtime.js:98:26
    at exports.trampoline.trampoline (/Users/james_zetlen/.nvm/versions/node/v0.12.5/lib/node_modules/keybase/node_modules/iced-runtime/lib/runtime.js:64:14)
    at Deferrals.exports.Deferrals.Deferrals._fulfill (/Users/james_zetlen/.nvm/versions/node/v0.12.5/lib/node_modules/keybase/node_modules/iced-runtime/lib/runtime.js:96:16)
    at ret (/Users/james_zetlen/.nvm/versions/node/v0.12.5/lib/node_modules/keybase/node_modules/iced-runtime/lib/runtime.js:29:18)
    at /Users/james_zetlen/.nvm/versions/node/v0.12.5/lib/node_modules/keybase/node_modules/iced-error/index.js:92:22
    at /Users/james_zetlen/.nvm/versions/node/v0.12.5/lib/node_modules/keybase/lib/command/proof_base.js:178:18
    at Deferrals.exports.Deferrals.Deferrals._call (/Users/james_zetlen/.nvm/versions/node/v0.12.5/lib/node_modules/keybase/node_modules/iced-runtime/lib/runtime.js:86:16)
```

**Comment by zetlen** [comment]
Do you plan to introduce a code coverage tool?

**Comment by maxtaco** [comment]
we plan to retire this client in favor of our new one.

**Comment by zetlen** [comment]
In Go?

**Comment by maxtaco** [comment]
yeah. i think your problem is having 2 public keys with the same UIDs.

Can you `gpg -k zetlen@keybase.io` for me?  those are your public key fingerprints, so they are safe to show.  I'm going to ask you to delete the one that's not  `DD1D 8801 710F 581A 63F6 C40B 3D82 F00E 8A3A 88B1`

**Comment by zetlen** [comment]
```
09:24 $ gpg -k zetlen@keybase.io
pub   4096R/44BE54B6 2015-07-19 [expires: 2025-07-16]
uid       [ultimate] keybase.io/zetlen <zetlen@keybase.io>
sub   4096R/CBCD2887 2015-07-19 [expires: 2025-07-16]

pub   4096R/8A3A88B1 2015-07-19 [expires: 2025-07-16]
uid       [ultimate] keybase.io/zetlen <zetlen@keybase.io>
sub   4096R/303CCFF8 2015-07-19 [expires: 2025-07-16]
```

**Comment by maxtaco** [comment]
Great, now try `gpg --delete-secret-and-public-key 44BE54B6`

**Comment by zetlen** [comment]
Like a charm. Thanks. I'll leave the issue open in case you want to reference it for the faulting fix commit.

**Comment by maxtaco** [comment]
Oh that's great, glad to hear it.  Sorry you wound up in a pickle.
