### ISSUE TITLE
`keybase encrypt --sign` crashes when user config missing

### ISSUE THREAD

**Issue by lucaswerkmeister** [keybase/keybase-issues#1704]
```
$ keybase encrypt --sign lucaswerkmeister
warn: No config file found; tried '/home/lucas/.config/keybase/config.json'
✔ public key fingerprint: 6B89 5B8B 11A4 75B1 EC93 1698 FC46 2872 72AE 323F
✔ "lucaswerkmeistr" on twitter: https://twitter.com/lucaswerkmeistr/status/606211725667508225
✔ "lucaswerkmeister" on github: https://gist.github.com/ac28e636a0b428f843cd
✔ "lucaswerkmeister" on reddit: https://www.reddit.com/r/KeybaseProofs/comments/2x8fwd/my_keybase_proof_redditlucaswerkmeister/
✔ admin of lucaswerkmeister.de via HTTP: http://lucaswerkmeister.de/keybase.txt
✔ admin of the DNS zone for lucaswerkmeister.de
/usr/lib/node_modules/keybase/lib/command/encrypt.js:92
        args.push("--sign", "-u", sign_key.fingerprint(true));
                                          ^
TypeError: Cannot read property 'fingerprint' of undefined
    at Command.exports.Command.Command.do_encrypt (/usr/lib/node_modules/keybase/lib/command/encrypt.js:92:43)
    at /usr/lib/node_modules/keybase/lib/command/encrypt.js:240:21
    at /usr/lib/node_modules/keybase/lib/command/encrypt.js:244:15
    at /usr/lib/node_modules/keybase/lib/command/encrypt.js:230:24
    at Deferrals.exports.Deferrals.Deferrals._call (/usr/lib/node_modules/keybase/node_modules/iced-runtime/lib/runtime.js:86:16)
    at /usr/lib/node_modules/keybase/node_modules/iced-runtime/lib/runtime.js:98:26
    at exports.trampoline.trampoline (/usr/lib/node_modules/keybase/node_modules/iced-runtime/lib/runtime.js:64:14)
    at Deferrals.exports.Deferrals.Deferrals._fulfill (/usr/lib/node_modules/keybase/node_modules/iced-runtime/lib/runtime.js:96:16)
    at ret (/usr/lib/node_modules/keybase/node_modules/iced-runtime/lib/runtime.js:29:18)
    at /usr/lib/node_modules/keybase/node_modules/iced-error/index.js:92:22
```
I think this broke in a recent-ish update.

**Comment by lucaswerkmeister** [comment]
Note: the bug occurs for both self-encrypts and foreign-encrypts.

```js
# encrypt.js, line 91
sign_key = this.is_self ? this.them : this.tssc.me;
```

It appears that no matter who I encrypt to (`lucaswerkmeister` or, randomly chosen, `tom`), `this.is_self` is always `false`. `this.tscc` contains lots of information, but no `me`. In fact, `lucaswerkmeister` doesn’t occur at all anywhere in `this`.

**Comment by lucaswerkmeister** [comment]
Aaah! Mystery solved – I recently got a new home dir, and didn’t have a `config` (and therefore no `user.name` in it).

Having solved that problem, I now discovered that keybase will happily sign messages even when I’m not logged in. Is that intended?

**Comment by oconnor663** [comment]
If you log in and then log out, you'll be in a state we sort of call "configured". The client knows who you are, even though it doesn't have a valid session token for you. Since you don't need a server session to call gpg, the client is happy to keep doing that for you even when you're logged out.

I've pushed 6b0efc997cd35f642c98bcc48b8757bd94c94a14 so that we exit with a proper error message in the case you hit up top. Thanks for the report!

**Comment by lucaswerkmeister** [comment]
Great, thanks for the quick fix!
