### ISSUE TITLE
Error when using keybase on the command line

### ISSUE THREAD

**Issue by birdmeister** [keybase/keybase-issues#1778]
I've successfully installed 'keybase' for the command line.
When running 'keybase version' I get:
keybase (keybase.io CLI) v0.8.19
- node.js v4.1.0
- gpg (GnuPG/MacGPG2) 2.0.28
- libgcrypt 1.6.3
Identifies as: 'keybase.io node.js client v0.8.19 darwin'

With every command I get the following error message:
warn: You have not proven ownership of your key. Run `keybase push --update`.
/usr/local/lib/node_modules/keybase/lib/user.js:1570
              _this.sibkeys = [parsed_keys.get_key_manager(_this.merkle_data.eldest_kid)];
                                           ^

TypeError: parsed_keys.get_key_manager is not a function
    at /usr/local/lib/node_modules/keybase/lib/user.js:1570:44
    at Deferrals.exports.Deferrals.Deferrals._call (/usr/local/lib/node_modules/keybase/node_modules/iced-runtime/lib/runtime.js:86:16)
    at /usr/local/lib/node_modules/keybase/node_modules/iced-runtime/lib/runtime.js:98:26
    at exports.trampoline.trampoline (/usr/local/lib/node_modules/keybase/node_modules/iced-runtime/lib/runtime.js:64:14)
    at Deferrals.exports.Deferrals.Deferrals._fulfill (/usr/local/lib/node_modules/keybase/node_modules/iced-runtime/lib/runtime.js:96:16)
    at /usr/local/lib/node_modules/keybase/lib/user.js:1563:28
    at User.exports.User.User._verify (/usr/local/lib/node_modules/keybase/lib/user.js:1565:15)
    at /usr/local/lib/node_modules/keybase/lib/user.js:791:32
    at /usr/local/lib/node_modules/keybase/lib/user.js:798:27
    at Deferrals.exports.Deferrals.Deferrals._call (/usr/local/lib/node_modules/keybase/node_modules/iced-runtime/lib/runtime.js:86:16)

Get the same error when I execute 'keybase push --update', so I don't get any further.

**Comment by maxtaco** [comment]
Should be fixed in v0.8.20, let us know if not (and reopen).
