### ISSUE TITLE
Install failure on Mac OS X

### ISSUE THREAD

**Issue by picwell-james** [keybase/keybase-issues#1795]
On OS X 10.10.5, the homebrew beta install works fine, but the npm install fails (and I'd rather use real keybase than kbstage forever).

`npm-install -g keybase-installer` completes successfully, but `keybase-installer` fails with:

```
child_process.js:1162
    throw errnoException(err, 'spawn');
          ^
Error: spawn ENOTDIR
    at exports._errnoException (util.js:746:11)
    at ChildProcess.spawn (child_process.js:1162:11)
    at exports.spawn (child_process.js:995:9)
    at SpawnEngine.exports.SpawnEngine.SpawnEngine._spawn (/usr/local/lib/node_modules/keybase-installer/node_modules/iced-spawn/lib/cmd.js:162:26)
    at /usr/local/lib/node_modules/keybase-installer/node_modules/iced-spawn/lib/cmd.js:282:17
    at Deferrals.exports.Deferrals.Deferrals._call (/usr/local/lib/node_modules/keybase-installer/node_modules/iced-runtime/lib/runtime.js:86:16)
    at /usr/local/lib/node_modules/keybase-installer/node_modules/iced-runtime/lib/runtime.js:98:26
    at exports.trampoline.trampoline (/usr/local/lib/node_modules/keybase-installer/node_modules/iced-runtime/lib/runtime.js:64:14)
    at Deferrals.exports.Deferrals.Deferrals._fulfill (/usr/local/lib/node_modules/keybase-installer/node_modules/iced-runtime/lib/runtime.js:96:16)
    at /usr/local/lib/node_modules/keybase-installer/node_modules/iced-spawn/lib/cmd.js:277:28
```

**Comment by maxtaco** [comment]
Maybe it can't find gpg?  Can you send a `-v` output?

**Comment by picwell-james** [comment]
```
$keybase-installer -v
keybase-installer v1.0.3

$keybase-installer -d
debug: + cmd.run 1.0.3
debug: ++ Installer::run
debug: +++ Installer::test_gpg
child_process.js:1162...
    throw errnoException(err, 'spawn');
```

**Comment by maxtaco** [comment]
Is `gpg` available in your path?  This should be a better error.  But if not, you can install GPG tools or you can `brew install gpg`

**Comment by picwell-james** [comment]
Yes, it's available.
```
$ brew install gpg
Warning: gnupg-1.4.19 already installed

$ brew upgrade gpg
Error: gnupg 1.4.19 already installed
```

**Comment by maxtaco** [comment]
since the obviously things have been exhausted, i'd need to see the rest of the install log that you snipped out, otherwise it's hard for me to know...

**Comment by picwell-james** [comment]
Do you mean below
```
child_process.js:1162
    throw errnoException(err, 'spawn');
...
```
two comments up? It's identical to the error in the comment starting the issue.

**Comment by maxtaco** [comment]
Ah, you are correct, sorry.  Which version of node are you running?  `node --version`?

**Comment by picwell-james** [comment]
```
$ node --version
v4.1.1

$ npm --version #just in case?
2.14.4
```

**Comment by maxtaco** [comment]
ok, this might be the issue

nothing comes to mind, but maybe the right idea is to wait another ~1 week or so until we launch the new Go client for the production server.

**Comment by picwell-james** [comment]
Ok, thanks for your help, I'll give that a try.

**Comment by maxtaco** [comment]
Darn, couldn't repro it with 4.1.1
