### ISSUE TITLE
command line crash immediately upon login

### ISSUE THREAD

**Issue by pizzapie** [keybase/keybase-issues#1873]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

I've brought this issue up with my shell provider and they advised me to bring it up to keybase:

Immediately after entering my passphrase for `keybase login` the CLI always crashes with the following stack trace:

```
ratchet@wolfman $ keybase config
info: Updated file: /home/ratchet/.keybase/config.json
ratchet@wolfman $ less ~/.keybase/config.json 
ratchet@wolfman $ keybase login
Your keybase username or email: ratchet@devio.us
Your keybase login passphrase: ***************

Error: Unable to allocate ArrayBuffer.
    at Scrypt.run (/usr/local/lib/node_modules/keybase/node_modules/triplesec/lib/scrypt.js:305:11)
    at keys (/usr/local/lib/node_modules/keybase/node_modules/triplesec/lib/enc.js:157:30)
    at /usr/local/lib/node_modules/keybase/node_modules/triplesec/lib/enc.js:166:19
    at /usr/local/lib/node_modules/keybase/node_modules/triplesec/lib/enc.js:184:15
    at Deferrals.exports.Deferrals.Deferrals._call (/usr/local/lib/node_modules/keybase/node_modules/iced-runtime/lib/runtime.js:86:16)
    at /usr/local/lib/node_modules/keybase/node_modules/iced-runtime/lib/runtime.js:98:26
    at exports.trampoline.trampoline (/usr/local/lib/node_modules/keybase/node_modules/iced-runtime/lib/runtime.js:64:14)
    at Deferrals.exports.Deferrals.Deferrals._fulfill (/usr/local/lib/node_modules/keybase/node_modules/iced-runtime/lib/runtime.js:96:16)
```
-----BEGIN PGP SIGNATURE-----
Version: Keybase OpenPGP v2.0.49
Comment: https://keybase.io/crypto

wsFcBAABCgAGBQJWUihMAAoJEDR/nePSHI/wfpwP/jG1GItfSXF05F1es+gVN19i
tUL5q8TGU643tmsO6jMRubpEtZgZ4NWSjAIiMxuBUs+VPfHtYp2R7sChbDjgD3DX
iOaqnm0h5YMaTS/z2mC5qHABnmB0MGpNiq0fWfYKzHXrm35od23Yi5ng8mqU0bZF
APJJdYv//uiAxy4DOjZnhvjSDUIsRmb009dQ/6s7vZVI33CgTMJ4vA1uBnUguwP9
zJoTQbGreyGo3xT3PV6eMNUDOe1Tlhmz07v7djEGsFgh2v/8XcDGKeJWnRyYuzsQ
vXFseqO3CrG1dM039/JB1k6BRM2SbAgJkbC6f58fFEno7sBQNgq1ENDilXUR72la
fcldStP6HzADqu5EueEyFB9jaw2NWVHZt1sdhl3thdNjhEHtJ2UVEZ9uDl6aj+2I
peB/5u9qD7WyYvCq7mJsLPBcbfXN1avKPZEEH4wJYWBouIWWDYfu8E4ZgEC2i3Sn
ezC8DxlqMFsVIb2GKoBSsf/lvGCCe7EtPGCkFjo9XZ00yilYLmAu/ylW/OdOfuXS
0PQf+lUyFa3dNmggTTLp4cEzXGHkfKSZaYjIFJQx5GugbK7DMiE3jMXJncyG6zZB
H7Ya4klj23kJ6qSvZea1fKLyDSjNQwcgVeBNM+Yk21xZ3dZ4Bfx7qO3Dry5FtPRp
PqNpKxRLnPElJ9Ek53pW
=Ffmz
-----END PGP SIGNATURE-----

**Comment by maxtaco** [comment]
Which version of node are you running?  Can you run `keybase -d login` ?  Thanks.

**Comment by pizzapie** [comment]
Following is the output from keybase -d login:

```
ratchet@wolfman $ keybase -d login
debug: + opening config file: /home/ratchet/.keybase/config.json
warn: No config file found; tried '/home/ratchet/.keybase/config.json'
debug: - opened config file; found=false
debug: + testing GPG command-line client <default: gpg2 or gpg>
debug: | using GPG command: gpg2
debug: - tested GPG command-line client -> null
debug: Warning on pinentry init: Error: can only run on Linux and OSX
debug: + Load proxy CAs
debug: - Loaded proxy CAs
debug: + startup message
debug: | CLI version: 0.8.23
debug: | Platform info: {"versions":{"http_parser":"1.0","node":"0.10.35","v8":"3.14.5.9","ares":"1.9.0-DEV","uv":"0.10.30","zlib":"1.2.3","modules":"11","openssl":"2.2.2"},"arch":"ia32","platform":"openbsd","features":{"debug":false,"uv":true,"ipv6":true,"tls_npn":true,"tls_sni":true,"tls":true}}
debug: | Version info: ["keybase (keybase.io CLI) v0.8.23","- node.js v0.10.35","- gpg (GnuPG) 2.1.4","- libgcrypt 1.6.3","Identifies as: 'keybase.io node.js client v0.8.23 openbsd'"]
debug: - startup message
debug: + opening database file: /home/ratchet/.keybase/keybase.idb
debug: ++ DB::_init_db
debug: -- DB::_init_db -> 2
debug: - DB opened
debug: + session::load
debug: ++ opening config file: /home/ratchet/.keybase/session.json
debug: -- opened config file; found=false
debug: - session::load
debug: + session::check
debug: - session::check
Your keybase username or email: ratchet@devio.us
Your keybase login passphrase: **************
debug: + request to getsalt (https://api.keybase.io:443/_/api/1.0/getsalt.json?email_or_username=ratchet%40devio.us) (cookie=true)
debug: | Adding a custom CA for host api.keybase.io when tls=true
debug: - request to getsalt -> null

Error: Unable to allocate ArrayBuffer.
    at Scrypt.run (/usr/local/lib/node_modules/keybase/node_modules/triplesec/lib/scrypt.js:305:11)
    at keys (/usr/local/lib/node_modules/keybase/node_modules/triplesec/lib/enc.js:157:30)
    at /usr/local/lib/node_modules/keybase/node_modules/triplesec/lib/enc.js:166:19
    at /usr/local/lib/node_modules/keybase/node_modules/triplesec/lib/enc.js:184:15
    at Deferrals.exports.Deferrals.Deferrals._call (/usr/local/lib/node_modules/keybase/node_modules/iced-runtime/lib/runtime.js:86:16)
    at /usr/local/lib/node_modules/keybase/node_modules/iced-runtime/lib/runtime.js:98:26
    at exports.trampoline.trampoline (/usr/local/lib/node_modules/keybase/node_modules/iced-runtime/lib/runtime.js:64:14)
    at Deferrals.exports.Deferrals.Deferrals._fulfill (/usr/local/lib/node_modules/keybase/node_modules/iced-runtime/lib/runtime.js:96:16)
```
