### ISSUE TITLE
Error: Cannot find module 'cheerio'

### ISSUE THREAD

**Issue by luixxiul** [keybase/keybase-issues#1907]
On Windows 10, after ``npm i -g keybase-installer`` and ``keybase-installer``, I got the following error:

````
$ keybase version
module.js:340
    throw err;
    ^

Error: Cannot find module 'cheerio'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (c:\Users\Temp\AppData\Roaming\npm\node_modules\keybase\lib\sigchain.js:32:13)
    at Object.<anonymous> (c:\Users\Temp\AppData\Roaming\npm\node_modules\keybase\lib\sigchain.js:923:4)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
````

**Comment by luixxiul** [comment]
Uh, I've just forgot to install gpg4win..
