### ISSUE TITLE
keybase update errror (elcapitan, keybase 0.8.25, node 5.5.0)

### ISSUE THREAD

**Issue by dcoeurjo** [keybase/keybase-issues#2025]
I have npm errors  when updating the keybase tool (directory not found). Please find below a snippet of the ```npm-debug.log```

```
323 warn In keybase@0.8.25 replacing bundled version of string_decoder with string_decoder@0.10.31
8324 warn In keybase@0.8.25 replacing bundled version of read with read@1.0.5
8325 verbose stack Error: ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/.staging/colors-956d4650' -> '/usr/local/lib/node_modules/keybase/node_modules/keybase-installer/node_modules/colors'
8325 verbose stack     at destStatted (/usr/local/lib/node_modules/npm/lib/install/action/finalize.js:25:7)
8325 verbose stack     at FSReqWrap.oncomplete (fs.js:82:15)
8325 verbose stack
8325 verbose stack Error: ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/.staging/colors-956d4650' -> '/usr/local/lib/node_modules/keybase/node_modules/keybase-installer/node_modules/colors'
8325 verbose stack     at Error (native)
8326 verbose cwd /john/smith/
8327 error Darwin 15.3.0
8328 error argv "/usr/local/Cellar/node/5.5.0/bin/node" "/usr/local/bin/npm" "install" "-g" "/var/folders/tb/q48kr8kx2f743703m8dqkkzr0000gn/T/keybase_install_xrVW1AfEmzGj0J6T2bED9g/keybase-0.8.25.tgz"
8329 error node v5.5.0
8330 error npm  v3.5.3
8331 error path /usr/local/lib/node_modules/.staging/colors-956d4650
8332 error code ENOENT
8333 error errno -2
8334 error syscall rename
8335 error enoent ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/.staging/colors-956d4650' -> '/usr/local/lib/node_modules/keybase/node_modules/keybase-installer/node_modules/colors'
8336 error enoent ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/.staging/colors-956d4650' -> '/usr/local/lib/node_modules/keybase/node_modules/keybase-installer/node_modules/colors'
8336 error enoent This is most likely not a problem with npm itself
8336 error enoent and is related to npm not being able to find a file.
8337 verbose exit [ -2, true ]
```

**Comment by dcoeurjo** [comment]
well.. my keybase tool version was quite old. I've resintalled it from home-brew.. Closing this issue
