### ISSUE TITLE
Keybase.pub issues

### ISSUE THREAD

**Issue by BrandonIngalls** [keybase/keybase-issues#2265]
When attempting to access any user file like [this](https://a2.keybase.pub/) one, "Not found" is returned, not the expected file.

**Comment by BrandonIngalls** [comment]
@cjb

**Comment by cjb** [comment]
@BrandonIngalls Fixed. Thanks!

@strib 
```
2016-05-30T03:08:04.269520 ▶ [DEBU kbfs(FBO 76c0ec27) folder_branch_ops.go:505] 4a57bfab Setting head revision to 164 [tags:FBOID=9CcDPR3-0YPCzRkmPlCKqA]
2016-05-30T03:08:04.269590 ▶ [DEBU kbfs(FBO 76c0ec27) folder_branch_ops.go:3733] 4a57bfac Done: <nil> [tags:FBOID=9CcDPR3-0YPCzRkmPlCKqA]
panic: invalid newPtr BlockPointer{ID: , KeyGen: 0, DataVer: 0, Creator: } with oldRef blockRef{id: 01cffc81f82388a56daf9953e71b4b01fa3a860cdce31450bdb0f113993addec2b}

goroutine 538541975 [running]:
panic(0xe2e260, 0xc896526250)
        /usr/local/go/src/runtime/panic.go:464 +0x3e6
github.com/keybase/kbfs/libkbfs.(*nodeCacheStandard).UpdatePointer(0xc88297c640, 0xc863fd5a10, 0x21, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /root/build/gopaths/amd64/src/github.com/keybase/kbfs/libkbfs/node_cache.go:157 +0x658
github.com/keybase/kbfs/libkbfs.(*folderBranchOps).updatePointers(0xc8aad81000, 0x7efd7b7266a8, 0xc8a75e7880)
        /root/build/gopaths/amd64/src/github.com/keybase/kbfs/libkbfs/folder_branch_ops.go:2856 +0x200
github.com/keybase/kbfs/libkbfs.(*folderBranchOps).notifyOneOpLocked(0xc8aad81000, 0x7efd7b726768, 0xc8a2585aa0, 0xc840cae3f0, 0x7efd7b7266a8, 0xc8a75e7880, 0xc849a52030)
        /root/build/gopaths/amd64/src/github.com/keybase/kbfs/libkbfs/folder_branch_ops.go:2864 +0x8e
github.com/keybase/kbfs/libkbfs.(*folderBranchOps).applyMDUpdatesLocked(0xc8aad81000, 0x7efd7b726768, 0xc8a2585aa0, 0xc840cae3f0, 0xc88caf28a8, 0x1, 0x1, 0x0, 0x0)
        /root/build/gopaths/amd64/src/github.com/keybase/kbfs/libkbfs/folder_branch_ops.go:3135 +0x824
github.com/keybase/kbfs/libkbfs.(*folderBranchOps).applyMDUpdates(0xc8aad81000, 0x7efd7b726768, 0xc8a2585aa0, 0xc840cae3f0, 0xc88caf28a8, 0x1, 0x1, 0x0, 0x0)
        /root/build/gopaths/amd64/src/github.com/keybase/kbfs/libkbfs/folder_branch_ops.go:3188 +0x110
github.com/keybase/kbfs/libkbfs.(*folderBranchOps).(github.com/keybase/kbfs/libkbfs.applyMDUpdates)-fm(0x7efd7b726768, 0xc8a2585aa0, 0xc840cae3f0, 0xc88caf28a8, 0x1, 0x1, 0x0, 0x0)
        /root/build/gopaths/amd64/src/github.com/keybase/kbfs/libkbfs/folder_branch_ops.go:3602 +0x74
github.com/keybase/kbfs/libkbfs.(*folderBranchOps).getAndApplyMDUpdates(0xc8aad81000, 0x7efd7b726768, 0xc8a2585aa0, 0xc840cae3f0, 0xc84eac5c20, 0x0, 0x0)
        /root/build/gopaths/amd64/src/github.com/keybase/kbfs/libkbfs/folder_branch_ops.go:3202 +0x175
github.com/keybase/kbfs/libkbfs.(*folderBranchOps).waitForAndProcessUpdates(0xc8aad81000, 0x7efd7b721510, 0xc82a0d9020, 0xc8988cd5c0, 0x0, 0x0)
        /root/build/gopaths/amd64/src/github.com/keybase/kbfs/libkbfs/folder_branch_ops.go:3748 +0x4b3
github.com/keybase/kbfs/libkbfs.(*folderBranchOps).registerAndWaitForUpdates.func1.1(0x0, 0x0)
        /root/build/gopaths/amd64/src/github.com/keybase/kbfs/libkbfs/folder_branch_ops.go:3689 +0x131
github.com/keybase/kbfs/vendor/github.com/cenkalti/backoff.RetryNotify(0xc84eac5f00, 0x7efd7b768250, 0xc894e18ae0, 0xc84eac5ee0, 0x0, 0x0)
        /root/build/gopaths/amd64/src/github.com/keybase/kbfs/vendor/github.com/cenkalti/backoff/retry.go:32 +0x4d
github.com/keybase/kbfs/libkbfs.(*folderBranchOps).registerAndWaitForUpdates.func1(0x7efd7b7a6868, 0xc8752f9080, 0x0, 0x0)
        /root/build/gopaths/amd64/src/github.com/keybase/kbfs/libkbfs/folder_branch_ops.go:3676 +0x19b
github.com/keybase/kbfs/libkbfs.(*folderBranchOps).runUnlessShutdown.func1(0xc894e186c0, 0xc86c2382c0, 0x7efd7b7a6868, 0xc8752f9080)
        /root/build/gopaths/amd64/src/github.com/keybase/kbfs/libkbfs/folder_branch_ops.go:3646 +0x30
created by github.com/keybase/kbfs/libkbfs.(*folderBranchOps).runUnlessShutdown
        /root/build/gopaths/amd64/src/github.com/keybase/kbfs/libkbfs/folder_branch_ops.go:3647 +0x13e
```
log send a9a77b198c91daf68d69ff1c

**Comment by strib** [comment]
@cjb: Darn, I just got around to looking at this, and the log send doesn't include this panic, and neither do any of the existing logs on keybase.pub.  I don't suppose you happened to have copied the original log where you found this anywhere, did you?

**Comment by cjb** [comment]
No, I thought the log send would do that. :/ I wonder what could cause it to be missing.

**Comment by strib** [comment]
Sadly `log send` doesn't send the rolled-over files.  It probably should, at least if there are less than 10K lines in the current file.
