### ISSUE TITLE
Error: Cannot find module 'cheerio' on OS X

### ISSUE THREAD

**Issue by mpdehnel** [keybase/keybase-issues#2398]
I can't seem to do anything with Keybase any more. It was working fine for the last year or so, but has now died. I tried to do an update through the command line but it failed. I tried to install the new client (from the .dmg) but this fails before the login stage (just hangs).

<img width="1202" alt="screenshot 2016-07-20 20 07 27" src="https://cloud.githubusercontent.com/assets/237223/16999610/c1c9d70a-4eb6-11e6-9cd8-a0ac9db8c88c.png">

![screenshot 2016-07-20 20 16 56](https://cloud.githubusercontent.com/assets/237223/16999648/f16c0820-4eb6-11e6-8fd3-498e836eaf6c.png)

`module.js:328
    throw err;
    ^

Error: Cannot find module 'cheerio'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/keybase/lib/sigchain.js:32:13)
    at Object.<anonymous> (/usr/local/lib/node_modules/keybase/lib/sigchain.js:923:4)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)`

**Comment by maxtaco** [comment]
Try `npm uninstall -g keybase`

**Comment by mpdehnel** [comment]
Hmmm, thanks.

Still won't let me log in to the new keybase app. It just hangs on the login screen, same as above. I have deleted it from `Applications` and re-installed/run it.

**Comment by maxtaco** [comment]
Try `keybase log send`

**Comment by maxtaco** [comment]
And we'll take a look

**Comment by mpdehnel** [comment]
Do I need to install both the command-line version (i.e. with `npm`) and the app in the `.dmg`? When I uninstalled the `npm` version I didn't re-install it, but just opened the installer from the `.dmg`; I'm now getting simply `zsh: command not found: keybase`

**Comment by cjb** [comment]
Please could you try dragging the app from the .dmg to /Applications, then double clicking on it inside /Applications, and then running `keybase` in the terminal?

**Comment by mpdehnel** [comment]
That's exactly what I've done :-)

**Comment by cjb** [comment]
Thanks @mpdehnel.  @gabriel, any ideas here?

**Comment by gabriel** [comment]
Can you run:

```sh
 /Applications/Keybase.app/Contents/SharedSupport/bin/keybase log send
```

**Comment by mpdehnel** [comment]
Hmm. I rebooted my machine again and it seems to have cleared itself up. Not sure why it wasn't connecting / why it was hanging before!

**Comment by mpdehnel** [comment]
I've sent the logs, but not sure if it will catch anything as I've deleted / re-added the app several times...!

**Comment by cjb** [comment]
@mpdehnel what's the log ID that log send told you?  (you can send another set if you didn't keep a copy of it)

**Comment by mpdehnel** [comment]
Just updated the above comment :-)

**Comment by gabriel** [comment]
This is another instance of the KeybaseInstaller.app getting stuck when it's calling out to `keybase install` and rebooting fixing it.

This is the same issue as https://github.com/keybase/client/issues/3197

There are a couple possibilities:
- The KeybaseInstaller, NSTask execution isn't getting the terminationHandler callback. I attempted a patch here: https://github.com/keybase/client/pull/3376 but it didn't have any effect.
- `keybase` binary is hanging for some reason which could be terminal related or a bug in the go code
- The binary is signed and maybe Gatekeeper is deciding to block it
- Or something else?

**Comment by gabriel** [comment]
I'm gonna do more investigating since this seems to not be as rare as I thought

**Comment by gabriel** [comment]
@mpdehnel Is there anything in your /var/log/system.log around 07/20/2016 20:13:42.884 BST that looks weird?

**Comment by mpdehnel** [comment]
```
Jul 20 20:13:40 Heresiarch WindowServer[213]: send_datagram_available_ping: pid 522 failed to act on a ping it dequeued before timing out.
Jul 20 20:13:42 Heresiarch keybase.Helper[34535]: Starting keybase.Helper: 1.0.27
Jul 20 20:13:42 --- last message repeated 1 time ---
Jul 20 20:13:42 Heresiarch keybase.Helper[34535]: Request: version({
        })
Jul 20 20:13:59 --- last message repeated 1 time ---
Jul 20 20:13:59 Heresiarch WindowServer[213]: send_datagram_available_ping: pid 522 failed to act on a ping it dequeued before timing out.
Jul 20 20:14:07 Heresiarch networkd[225]: -[NETProxyLookup pacLookupComplete:proxies:error:] PAC evaluation error: Error Domain=kCFErrorDomainCFNetwork Code=2 "(null)" UserInfo={kCFGetAddrInfoFailureKey=8}
Jul 20 20:14:09 --- last message repeated 2 times ---
Jul 20 20:14:09 Heresiarch WindowServer[213]: send_datagram_available_ping: pid 522 failed to act on a ping it dequeued before timing out.
Jul 20 20:14:09 Heresiarch UserEventAgent[52]: Failed to send message because the port couldn't be created.
Jul 20 20:14:09 Heresiarch UserEventAgent[296]: com.apple.TMHelperAgent.SetupOffer enabled
Jul 20 20:14:11 Heresiarch networkd[225]: -[NETProxyLookup pacLookupComplete:proxies:error:] PAC evaluation error: Error Domain=kCFErrorDomainCFNetwork Code=2 "(null)" UserInfo={kCFGetAddrInfoFailureKey=8}
Jul 20 20:14:19 Heresiarch WindowServer[213]: send_datagram_available_ping: pid 522 failed to act on a ping it dequeued before timing out.
Jul 20 20:14:29 Heresiarch networkd[225]: -[NETProxyLookup pacLookupComplete:proxies:error:] PAC evaluation error: Error Domain=kCFErrorDomainCFNetwork Code=2 "(null)" UserInfo={kCFGetAddrInfoFailureKey=8}

```

If I `less /var/log/system.log | grep keybase` the output is:

```
Jul 20 20:13:42 Heresiarch keybase.Helper[34535]: Starting keybase.Helper: 1.0.27
Jul 20 20:13:42 Heresiarch keybase.Helper[34535]: Request: version({
Jul 20 20:25:31 Heresiarch keybase.Helper[34535]: Request: version({
Jul 20 21:16:48 Heresiarch keybase.Helper[34535]: Request: version({
Jul 20 21:21:28 Heresiarch keybase.Helper[34535]: Request: version({
Jul 20 21:21:28 Heresiarch keybase.Helper[34535]: Request: version({
Jul 20 21:31:32 Heresiarch keybase.Helper[34535]: Request: version({
Jul 20 21:58:42 Heresiarch keybase.Helper[34535]: Request: version({
Jul 20 22:09:02 Heresiarch keybase.Helper[829]: Starting keybase.Helper: 1.0.27
Jul 20 22:09:02 Heresiarch keybase.Helper[829]: Request: version({
Jul 20 22:09:02 Heresiarch com.apple.xpc.launchd[1] (keybase.updater): This service is defined to be constantly running and is inherently inefficient.
Jul 20 22:09:02 Heresiarch com.apple.xpc.launchd[1] (keybase.service): This service is defined to be constantly running and is inherently inefficient.
Jul 20 22:09:03 Heresiarch keybase.Helper[829]: Request: kextInstall({
Jul 20 22:09:03 Heresiarch keybase.Helper[829]: Kext loaded? 0
Jul 20 22:09:03 Heresiarch keybase.Helper[829]: Loading kextID: com.github.kbfuse.filesystems.kbfuse (/Library/Filesystems/kbfuse.fs/Contents/Extensions/10.10/kbfuse.kext)
Jul 20 22:09:04 Heresiarch keybase.Helper[829]: Request: createDirectory({
	    directory = "/keybase";
Jul 20 22:09:04 Heresiarch com.apple.xpc.launchd[1] (keybase.kbfs): This service is defined to be constantly running and is inherently inefficient.
```
