### ISSUE TITLE
saving a backup via "bup" to kbfs dir fails

### ISSUE THREAD

**Issue by soulware** [keybase/keybase-issues#2578]
I am attempting to setup bup (https://bup.github.io/) against a BUP_DIR on a kbfs mount at `/keybase/private/<username>/bup`. 

Something is not happy in the bup git internals when attempting to run `bup save` -

```
Reading index: 7, done.
Saving: 100.00% (2/2k, 7/7 files), done.    
Traceback (most recent call last): 
  File "/usr/local/Cellar/bup/0.28.1/lib/bup/cmd/bup-save", line 460, in <module>
    w.close()  # must close before we can update the ref
  File "/usr/local/Cellar/bup/0.28.1/lib/bup/bup/git.py", line 790, in close
    return self._end(run_midx=run_midx)
  File "/usr/local/Cellar/bup/0.28.1/lib/bup/bup/git.py", line 776, in _end
    os.fsync(self.parentfd)
OSError: [Errno 5] Input/output error
```

Is this a known limitation in kbfs?

**Comment by maxtaco** [comment]
Hi Simon, can you do a 'keybase log send'?

**Comment by soulware** [comment]
Sending now.

**Comment by soulware** [comment]
Do you need the log id? And does this need to be sent to you privately?

**Comment by maxtaco** [comment]
No, it can be sent publically, thanks!

**Comment by soulware** [comment]
Log id: `9c9650efb4ce87c140cb3f1c`

**Comment by strib** [comment]
Thanks for the report.  Huh, it loos like `bup` tries to run `fsync` on a directory, which we haven't yet implemented.  I'll make sure we have a ticket for t internally.  Sorry for the inconvenience!
