### ISSUE TITLE
Fixes for documentation: Merkle Root in Bitcoin Blockchain

### ISSUE THREAD

**Issue by sbosshardt** [keybase/keybase-issues#3027]
Issues with [merkle_root_in_bitcoin_blockchain](https://keybase.io/docs/server_security/merkle_root_in_bitcoin_blockchain) documentation
====================

Background Info:
------------------------
I don't have much experience with Python. I was able to stumble my way through the tutorial by searching online for Python programming topics (e.g. how to get the first property of an object).

The beginning part of the tutorial causes you to use the latest hash published by keybase. However, in order to follow / verify the later parts of the tutorial, 

System tested on:
-------------------------
Linux Mint 18 (based on Ubuntu 16.04)
Python 2.7.12.

> Python 3 had a different problem and failed earlier in the tutorial than Python 2, so I assumed I was supposed to type the "python" command into the shell to start the REPL, not "python3". The documentation did not specify whether the code was written for Python 2 or Python 3. (The Python 3 error I got before giving up was: ```ImportError: No module named 'urllib2'```)

Commands in the documentation didn't work without modification:
-----------------------------------------------------------------------------------------------

### 1.)  This line of code did not work:
```from pycoin.encoding import bitcoin_address_to_hash160_sec, hash160```

The error message was:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named pycoin.encoding```
```
I searched online to find pycoin and read the installation instructions. To install pycoin, I needed to install pip first.
```
sudo apt install pip
pip install pycoin
```
After that, I was able to open the python interactive shell and progress past that point.

### 2.) This line of code appears to be based on a different json structure than what was downloaded:

```
sig = b64decode(re.compile(r"\n\n((\S|\n)*?)\n=").search(root_desc['sig']).group(1))
```
Error message:

```
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
KeyError: 'sig'
```

I was able to isolate the cause of the error. Running ```print root_desc['sig']``` would cause the same error.

When I looked at the [JSON being downloaded](https://keybase.io/_/api/1.0/merkle/root.json?hash160=09342ed2c3268fdc5f49e1465c9eac34ee236e44) (running ```print uri``` from the interpreter, loading the URI with my web browser, and sending the JSON through a [pretty-print](http://jsonprettyprint.com)), it didn't match what I expected it to look like.

I expected the JSON structure would look something like this:
```
{"sig": "-----BEGIN PGP MESSAGE-----..."}
```

Instead, it looked something like this:
```
{"sigs": { "010159baae6c7...": { "sig": "-----BEGIN PGP MESSAGE-----..." } } }
```

I was able to get past this hurdle by changing ```root_desc['sig']``` to ```root_desc['sigs'][root_desc['sigs'].keys()[0]]['sig']```. (There might be a better way to write this but I have limited Python experience)

### 3.) Potential improvement: Don't run assert commands in the interactive shell.
Running ```assert (to_addr_hash == hexlify(hash160(sig)))``` produces no output. Output is only produced if the assertion fails. Removing the ```assert ``` from the line of code causes the interactive interpreter to print the word "True" (as does substituting ```print``` for ```assert```).

### 4.) The root_hash assignment statement did not work:
```
root_hash = json.loads(re.compile(r"({[\x00-\x7f]*})").search(sig).group(1))['body']['root']
```
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting object: line 1 column 1035 (char 1034)
```

This looks like another case of a changed JSON structure. The regex is loading an incomplete part of JSON - there are two unclosed curly braces (and no "root" property of "body").

Now, if we use the PGP signed message that was hashed [on the blockchain](https://blockchain.info/address/168bJepnpoZkoW5AWE7TxNhvuNPmsNmyvS) as of the time the tutorial was written, this statement works. But the structure of the JSON within the PGP signed message has changed.

Since I am trying to follow the tutorial as it is, I was using the most recent [(Aug 5 2017) bitcoin transaction with receiving address 1qfbTaHcQzLcxWb2wEizzWw8uVs3maaKD](https://blockchain.info/tx/c2b27e429b984ad758ae06ca829830682ad4379dc18c35c2910af8b2bce5dc25). When I run the regex by itself (not feeding it into json.loads()), here is the output I see:
```
>>> re.compile(r"({[\x00-\x7f]*})").search(sig).group(1)
'{"body":{"kbfs":{"private":{"root":"iKNlcGvEIKmql0M6vfdOf/oUMcRJG3NZiKoVQbminOZfZROihW4DoWjEQH94E6Kmt/Fc2EXIRkWua1nLQJre1NsWuxkuhXQ64E2rKJ+H/JvRlPoUrT/Us9aGDcQrJECbclM/YlWn5RC6OE2jbm9uxBjsT1XzFhHSkrc6LGP9nb1lTN5uE6gZEDmicHLEQAmBlQSm9eWBoygFdmUTb2rBf61rbh3qj3Nn/g5t2dXjK0lfXZkrr6HvslypFLYTQ/9F4SpSvS91IcQZ+kPvWzqic27NL4ShdAKidHPOWYU7v6F2AQ==","version":1},"privateteam":{"root":"iKNlcGvEIEpRPOIFe3rPZpsle17VgB2b7sn9bcqXufbl7LiB9y89oWjEQL5JhDUiijtrtkh7sXdGADnZmE6AChD4wtvR880BC0prGlGDtesqwwy2+pUMEJRcdJQPUibxE4/yBIlZ+B/5x9Kjbm9uxBgLjxM2iyomT23GPXNYTvl60npvRYHNRAmicHLEQBsYvxKE8jwyi9YzCdDvTlIqiXnJhuN2tKaPToRyOEqxwURuP3Use37OPOKLnr5U2m+Mx85eceu7VybGA2n/2U+ic27NA0yhdAOidHPOWYU7v6F2AQ==","version":1},"public":{"root":"hqFoxECTlziCy0Yl5QUQD/rts6eKLWNjHnKBVtd1D0J3LTFZUi01RlhuaTbY3NUj6LDDVsbxEP3Eu17TPOFG8Rnqjws8onByxED8PYJ5s9jpP/qOBUEinAX64zpGrhLyI91SNjRo8iiz8LwxpJ0IUo3lcuepfKXZaXE8v/cAVC1lTDNitW0rdD5+onNuzS+NoXQBonRzzlmFO7ChdgE=","version":1}},"key":{"fingerprint":"03e146cdaf8136680ad566912a32340cec8c9492","key_id":"2A32340CEC8C9492"}'
```
Which, as I mentioned earlier is incomplete - it has unclosed curly braces and is missing the "root" property of "body").

If I use the PGP signed message from July 14th 2014, the regex works as intended:
```
>>> re.compile(r"({[\x00-\x7f]*})").search(sample_sig).group(1)
'{"body":{"key":{"fingerprint":"03e146cdaf8136680ad566912a32340cec8c9492","key_id":"2A32340CEC8C9492"},"prev":"ad261859d559864b47af3ea5ed0a1720ed6c1f154ba86f0bae2f3e2ae8c979b6dbc2317a47987248434c1a44eb855a143ef1bf33768f025c26098ff1bf0e80d0","root":"c6f881691c7a5126d5334c8fd9af2d240025e34cd5c6618ac6dae0737abad20354104df6c2c8ebbbc4970aedf3a92bdb42d20441d639309a8f7d375c80f7bf09","seqno":27178,"txid":"fcd00c4f58db83d731ba6bc203c13215","type":"merkle_root","version":1},"ctime":1405330379,"tag":"signature"}'
```

This is because the contents of the ```sig``` variable are significantly different. I went ahead and followed the tutorial a second time to troubleshoot, prefixing all variable names with "sample_" in order to follow the data Max was working with at the time the tutorial was written.

Here is the output for the signature from July 2014:
```
>>> sample_sig
'\x90\r\x03\x00\x02\x01\xf48\x03\xa3I\xda\x99\xd5\x01\xcb\xc1?b\x00S\xc3\xa3\xcb{"body":{"key":{"fingerprint":"03e146cdaf8136680ad566912a32340cec8c9492","key_id":"2A32340CEC8C9492"},"prev":"ad261859d559864b47af3ea5ed0a1720ed6c1f154ba86f0bae2f3e2ae8c979b6dbc2317a47987248434c1a44eb855a143ef1bf33768f025c26098ff1bf0e80d0","root":"c6f881691c7a5126d5334c8fd9af2d240025e34cd5c6618ac6dae0737abad20354104df6c2c8ebbbc4970aedf3a92bdb42d20441d639309a8f7d375c80f7bf09","seqno":27178,"txid":"fcd00c4f58db83d731ba6bc203c13215","type":"merkle_root","version":1},"ctime":1405330379,"tag":"signature"}\x89\x02\x1c\x04\x00\x01\x02\x00\x06\x05\x02S\xc3\xa3\xcb\x00\n\t\x10\xf48\x03\xa3I\xda\x99\xd5\x90\xc7\x10\x00\xd4{\xc9\xf1\xe80\r\r\x88p\xf9=\x82\xaf:\xec\xa3\xc78\xe3;\x9d^\x1f\xa3\xc7%"V\xb4\xc80\xfa\xe4\xc4Vv\xc9\x85\xab\xe0K\xa8\xd5%@\xe5j\x0e\xaa\x0eQ\xbb_j\x98L\xfe\xbd\xe5\xc9\xbd\x84\xf28\n\xd4f\xb8b\x19\x95{%\xf3\x04\x9e\x92u\xd8\xad\xdd\xb8\x85\x1d\xb0\x93]2\xc2\xb5\x1b\xb0\xc4ii\x8c\x86(\xd6\x10\x18\x96\x86.\x9ar\x1f\xdfc2\xbe\x0bBU\xf1\xa4\x00$n\x8f\xadj\xd4\x8dwY\xfc\x04\x12}{\x14\x9c\x13H\xb7\xb4B\x0cr9?\x85\x02\xac@$\x82{\x90\xb1[/\x80X\xe3\xd2\xb1FT\x83\x1d\xdd\xfd\n\xee\xf13\xcbr\x01\x86\xb5\x89W\xfe\xf8\xb1\x19(o\x82w\xcc\x01\xc8\xf4]xA\xebV$\x8d\x89\x18h\xd0\xea\xaa\xadMM\xde\x1d\x1b\xbc#\xdbB0u\x98\x17\x86\x01J\xd2S\xbe\x80\x1e\xb0\xfe\xf3\xa4\xdex\xfd\xd2m}^o\xeb\xd4I\xe4\x14i\x93\x81;>\x02\xf6\xce\xf0\xf5\xa5\xb6\x9a\xfez\xd9\xc6.{\x0b\x042+g\xff\x01\xd6\x1d\x83\x97\x08D\xce\xec\xdc\xff\xf2\xcc\x19E\xe0U0\x83\x99&\xa6W\xcf\xca\x9f\xfb\xf8\x92\xc0\xa2\x9b\xa8\t\x847\xe0\x8c\xe3\x9aQ\x06\xf7\xc55\x9d&\xd604\xcb\xca\x1f\x98\x14\xf4\x91A\xbc1\xde\xb5\xbdG<K\xdc\x0eK\x8c\xb7\x89Wa\xe0!&m\xf4Xs\tgK\x18\xd7i3\x97\xd2_\x11AO)\xc33B\x07t*\xa8 \xe0\x95X\xba\x18\ne\xfb\x15\xf2\xd8\x10\x1b\x07V_\xd5\x80\xc3\xbe#\x07\xf7\xb6\xc6Y5\x9a}\xff5d\xa5r\xb18\xd9<\x98\xa8\xc6`M\xabH\xea\xccI\x898o\xfdf\xa2\x8c\xbd\xfe\x7fLe\xef\xcd\x89B\xe6\xc6PBBhQ.jp&\xe8\xb8\xdc\x83\x03%\x1b\xf2\xdbq\xf9\x01O\xc2\xe2\xa5\xaf\x13:}\xc8WP\xbb\x82"m=\x97\x0e\x98\xffB\xf9\xeff;\x99F\xee\xd9\x1d:\xa0\xac\xca\xc7\x0c\xdc\x16\x14\xeai<\xf4?KBEy@,:wq]\xa1\xd0#'
```

The output for today's signature has much more data:
```
>>> sig
'\x90\r\x03\x00\x08\x01\xf48\x03\xa3I\xda\x99\xd5\x01\xcb\xebb\x00Y\x85B\xac{"body":{"kbfs":{"private":{"root":"iKNlcGvEIKmql0M6vfdOf/oUMcRJG3NZiKoVQbminOZfZROihW4DoWjEQH94E6Kmt/Fc2EXIRkWua1nLQJre1NsWuxkuhXQ64E2rKJ+H/JvRlPoUrT/Us9aGDcQrJECbclM/YlWn5RC6OE2jbm9uxBjsT1XzFhHSkrc6LGP9nb1lTN5uE6gZEDmicHLEQAmBlQSm9eWBoygFdmUTb2rBf61rbh3qj3Nn/g5t2dXjK0lfXZkrr6HvslypFLYTQ/9F4SpSvS91IcQZ+kPvWzqic27NL4ShdAKidHPOWYU7v6F2AQ==","version":1},"privateteam":{"root":"iKNlcGvEIEpRPOIFe3rPZpsle17VgB2b7sn9bcqXufbl7LiB9y89oWjEQL5JhDUiijtrtkh7sXdGADnZmE6AChD4wtvR880BC0prGlGDtesqwwy2+pUMEJRcdJQPUibxE4/yBIlZ+B/5x9Kjbm9uxBgLjxM2iyomT23GPXNYTvl60npvRYHNRAmicHLEQBsYvxKE8jwyi9YzCdDvTlIqiXnJhuN2tKaPToRyOEqxwURuP3Use37OPOKLnr5U2m+Mx85eceu7VybGA2n/2U+ic27NA0yhdAOidHPOWYU7v6F2AQ==","version":1},"public":{"root":"hqFoxECTlziCy0Yl5QUQD/rts6eKLWNjHnKBVtd1D0J3LTFZUi01RlhuaTbY3NUj6LDDVsbxEP3Eu17TPOFG8Rnqjws8onByxED8PYJ5s9jpP/qOBUEinAX64zpGrhLyI91SNjRo8iiz8LwxpJ0IUo3lcuepfKXZaXE8v/cAVC1lTDNitW0rdD5+onNuzS+NoXQBonRzzlmFO7ChdgE=","version":1}},"key":{"fingerprint":"03e146cdaf8136680ad566912a32340cec8c9492","key_id":"2A32340CEC8C9492"},"legacy_uid_root":"0c58a74abcb1db656146ebf667b5ea5cc55e208fbb534cd1b1e9454890358e5e","prev":"b577d7cfc38ca1ddf75c1ed467002aaf18868f9fbcc9e95e047b2db52dccdce9ee52d70a49af490a8346cd7ecdc8304ab5c9f30522b13c07fa5450a74853e8d2","pvl_hash":"8389a61cf8e200eb04da9339c4d117446e5e3e49a94b90ddf7a7012675c8b39eee5872c225d32f2af371b61a6fda1b87265f54f32facd0d41afeaa67eea95b6f","root":"11a286a735dbc42c9a111868cdc58a5ab90ee6e19ffee06937116824da3968c0aaca5979d2ef3fd085162ef58e9a60d7303657c4a3a89320503336f4e7f415ba","seqno":1305694,"skips":{"1043550":"21f9e062ebfebc2fae9503d7e8a8f2517f0678d4f6bb1f1a556782abd7bb8b4f","1174622":"fda61f3e27f6df3ca5c4e13f151d1c2daee260a8721362b87e8d4a8b6b5d691e","1240158":"622023be8a5a7c4019069b39f64beb6da682559a6c09046ad130efd047d93d95","1272926":"9703d7284a3b6a1f42aeaacdd160e7d92437895d35bba7f333cc13b38d77b388","1289310":"2b6cb4c35a1b79efe01bed1154d68e117ca8b14d97494734dacd2a20976fe27b","1297502":"43523ad199b7cb792ec7a04cad1bf2d80395c5fd7fed3a469da094785e675f37","1301598":"1d70c\xea6b6726563f3d8b5e14c9640415c7455ef508f73d3bfb23654add15498ea","1303646":"fb937a2d30dc619c32acf3337fe671ef63bc3dd281b21d125f6d77b987e0a837","1304670":"06cb70a3ce3f469ec8899c207b7c0f1dd3516a3f22dd1eb0f6ea1dd9501882be","1305182":"af55d0b13a59982b73997857946c163b24696e6e71c08ce7094b7a46f7832530","1305438":"e763a3a1320b13bfbedd48d6f737c27fc77a5d7ae8297b2868fb88b2b7954c30","1305566":"9e6b1d2c788afb311736943f20a3457c5a6039a6be6f624df891690f157ff9b8","1305630":"df0fd49bfcded18f4ab6c962618546128d1e41f22efec6ee237c1e674735e67e","1305662":"a9772798d78950d9769fdba352c03a7340b6bb68ead097c8037a5cde7c24e7e5","1305678":"b6b1d112eda79fc6ee621e469dfde16039f7d8babeed6ed705585f3ee7604999","1305686":"861195b86ebd2a95344d5dce98a81aa3b4a37c30dafb7b4a45eac251f8649f18","1305690":"ac100f2203768873c3be4124a9b4dd7872ded1db1a05384b8c17af3666e2ba1f","1305692":"89a0a44b15101cfeda22d88f340b8c5c188202d412cbda52206d396517c6e8e0","1305693":"2d756384c7eb049a2e003e6be5a89875989123de44ec590ed743f0ba3b3feb7e","257118":"85a20255d4e6f6b33c2151438a8f3\xc0\x17bb477dcef06f8d8f68706da70c64477ee72","781406":"0c3648f494447fb9f35f81ef5fe705f49c3ce20ea5a643285c63e32cfc48444a"},"txid":"e3475f4dc36239665e33868351e17a15","type":"merkle_root"},"ctime":1501905580,"tag":"signature"}\x89\x02\x1c\x04\x00\x01\x08\x00\x06\x05\x02Y\x85B\xac\x00\n\t\x10\xf48\x03\xa3I\xda\x99\xd5\x97\x08\x0f\xfb\x06\xf7\xc31\x98\x94\xc7\xec\x18\xb5\x7f6\x83D\xec\x19\xfbf\x996\xff\xac\xf5J\x08\x19TVN\xde\xc7\xef_\x16~\xa5\xb5\x04\xe5s\xbaW?\xfe\x88\x88\xb4e\x89M\xe4\x10)u\xf3\xcb\x04@H-gu\x02\t\xdfx\r\xfbU\xc9\x82\x11@i\xe9:\x13#\xc9*\xc9\xffDq\xcb\xcc\x04\xc6\xc9\xc3\xces"\x1e]V\xcb!\xc8\x95\xe0|\xda\xe0\xd5_\xacR7}\x8aW{T\xf18N~\x86,\xa1\xe0\x18\xd0\n\xbd\x0b\xe0\xd7T8S\xd8\xca\xca\xef\x81\x93\xa7$W\xfe\x08\x1f\x9b\xd0oZ\x12\xce\x050\xcfn\x90]k)\xec8\x19c\xd7=\xd4\xa4\x86v\xdex>\xd1%\xea\x10\xec)z`No\xb7W\x02\x8eg\xc1\xa78\x1e+\x97\x10\xb8\x1a\xdc/\xd2\x7f\xfbr\xad\xec\xcf\x96\xcb\x03\xa7\x8e\xd1\xc7|s\x82\xe7\x04\x9cG\xc7\x97_X\xb0\x18\xedP\xfd5\xaeA\xb8\xe9\xcc\x0f^l\x9b\x88\xf1\xaf8F\xc7\xd0\xe4\xf8/Pb$\x83\xdd\x9ed-4\xe88\x88\x1e\x87M\x94;\x9d\x8b\xcd\xea\x84\xd1\xf74P\xf8\x0fp7\x9e\x05\x96\xbb\xde(!^\xbeO\x02\xb2\x90m\xd4\xb5\xf9\x96B\xbb7DZ\x81\x01(vq\x11y\x1aD{\x03a+\xe4t\xcd\x86\xb4\x0b\xeeb\xe8\x83\xe5\xa2fY\xb9\x96x\xa3\xdbQ\xe2\x1f\xc7W\x8fViU\xa8\xf31\x8a\x15M>\xab#\x97\x95\xd9\xb2~NBw\xd2af@+=\xbb\x94\xa3t\xaf\xc8CZ,\x9e\xea\xf2.\x8c\xc0C\xe8\xa7\nfU\xb9\xb4\xeaZ\xfb]-\xfa\x1d\x05\xd0\xe3\xf05\x96;\xb0\xd14\x15\xc9\x8dm?>\xa2-L;\x1bY)m&<B&BT\xa2\x19\x81|6Y\xfboK\xab\xa4V^\xbd\x0bQuc\x10\xa31"\xb5$\xf3g\t\x1f8\x0f\xc5\xc4\xabo\xf1\x14 q\x1c\xa8\xd1\r\xc3\x0c-\xb1^\x17\x81\xdf\x95u\xfdN\xf1\x96jo\x1eS\x859c\xc3Ib\x16\xe8D\xff\x95h\xeb\xa6m^*\x97\xc7zts\xac\x10yEM,'
```

I don't know what all the output with ```\x``` is, I know that they are for some sort of binary data. Another problem is that there are three of these within the JSON, and it makes the JSON invalid.

It took me a while, but I was ultimately able to craft a regex that extracts the JSON (assuming that the three unprintable characters should be deleted). So much for what was supposed to be "quick and dirty".
```
re.sub(r'[\x00-\x08\x0b\x0c\x0e-\x1f\x7f-\xff]', '', re.compile(r"({.*\"})").search(sig).group(1))
```

Putting it together:
```
root_hash = json.loads(re.sub(r'[\x00-\x08\x0b\x0c\x0e-\x1f\x7f-\xff]', '', re.compile(r"({.*\"})").search(sig).group(1)))['body']['root']
```

----------

At this point, I decided to give it a rest. I got about halfway through the tutorial and it took me significantly longer than I expected. If I pick up from where I left off and find more, I'll consider adding it to this issue.

**Comment by maxtaco** [comment]
thanks for the report, I'll give it a look.

**Comment by maxtaco** [comment]
I've fixed the primary problem, which is this:

```python
 keybase_kid = '010159baae6c7d43c66adf8fb7bb2b8b4cbe408c062cfc369e693ccb18f85631dbcd0a'
sig = b64decode(re.compile(r"\\n\\n((\\S|\\n)*?)\\n=").search(root_desc['sigs'][keybase_kid]['sig']).group(1))
```

We're eventually going to transition to another public key for signing the Merkle Root, and wanted to have the ability to sign with two keys concurrently. Hence, we added another level in that JSON object to index the signature with the Key ID of the key used to generate the signature. We forgot to update the Docs, thanks for finding this mistake!

BTW, everything seems to work after this fix, I ran the script fine in Python 2.7.

**Comment by maxtaco** [comment]
here's my full script:

```python
from   urllib2 import urlopen
import json
from_addr = "1HUCBSJeHnkhzrVKVjaVmWg2QtZS1mdfaz"
uri       = "https://blockchain.info/address/%s?format=json" % (from_addr)
to_addr   = json.load(urlopen(uri))['txs'][0]['out'][0]['addr']
from pycoin.encoding import bitcoin_address_to_hash160_sec, hash160
from binascii import hexlify
to_addr_hash = hexlify(bitcoin_address_to_hash160_sec(to_addr))
print to_addr_hash
kb        = "https://keybase.io/_/api/1.0"
uri       = "%s/merkle/root.json?hash160=%s" % (kb, to_addr_hash)
root_desc = json.load(urlopen(uri))
print root_desc
import re
from base64 import b64decode
sig = b64decode(re.compile(r"\n\n((\S|\n)*?)\n=").search(root_desc['sigs']['010159baae6c7d43c66adf8fb7bb2b8b4cbe408c062cfc369e693ccb18f85631dbcd0a']['sig']).group(1))
print hexlify(hash160(sig))
assert (to_addr_hash == hexlify(hash160(sig)))
```

**Comment by jeffallen** [comment]
The next part of the web page is failing now.

```python
root_hash = json.loads(re.compile(r"({[\x00-\x7f]*})").search(sig).group(1))['body']['root']
```

That fails with:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting object: line 1 column 1035 (char 1034)
```

This is because there are currently binariy characters in the sig, a \xc0 and a \xea. If you modify the RE to include those, the resulting string is not accepted as UTF8 and at that point I gave up:

```
>>> root_hash = json.loads(re.compile(r"({[\x00-\x7f\xea\xc0]*})").search(sig).group(1))['body']['root']
root_hash = json.loads(re.compile(r"({[\x00-\x7f\xea\xc0]*})").search(sig).group(1))['body']['root']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xea in position 7: invalid continuation byte
```

**Comment by maxtaco** [comment]
Repro'ed.  My poor man's PGP parser has hit a wall

**Comment by maxtaco** [comment]
We'll investigate it, thanks....

**Comment by jeffallen** [comment]
Yes! Works for me!

**Comment by maxtaco** [comment]
Ok great we will publish it to the live site today.

**Comment by maxtaco** [comment]
Thanks for the help.
