### ISSUE TITLE
think I broke "keybase chat api"

### ISSUE THREAD

**Issue by antiochp** [keybase/keybase-issues#3072]
I sent a "large" message in a private chat to another user.

Running `keybase chat read` and choosing the conversation gives this - 

```
[outbox message: state: <error> contents: { ... }
```

But trying to run `keybase chat api` and passing in the json to read the same conversation panics like this - 

```
panic: wrong case accessed

goroutine 1 [running]:
github.com/keybase/client/go/protocol/chat1.MessageUnboxed.Valid(0x3, 0x0, 0x0, 0xc4202a4c00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/build/go/src/github.com/keybase/client/go/protocol/chat1/local.go:1884 +0x9d
github.com/keybase/client/go/client.(*chatServiceHandler).ReadV1(0xc42000e008, 0x83600e0, 0xc420080008, 0xc42029a410, 0xc, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/build/go/src/github.com/keybase/client/go/client/chat_svc_handler.go:178 +0x8be
github.com/keybase/client/go/client.(*ChatAPI).ReadV1(0xc420150060, 0x83600e0, 0xc420080008, 0x0, 0x0, 0x0, 0xc42029a0a0, 0x4, 0x0, 0xc420156090, ...)
	/Users/build/go/src/github.com/keybase/client/go/client/chat_api_handler.go:333 +0x299
github.com/keybase/client/go/client.(*ChatAPIDecoder).handleV1(0xc420723b60, 0x83600e0, 0xc420080008, 0x0, 0x0, 0x0, 0xc42029a0a0, 0x4, 0x0, 0xc420156090, ...)
	/Users/build/go/src/github.com/keybase/client/go/client/chat_api_decoder.go:80 +0x308
github.com/keybase/client/go/client.(*ChatAPIDecoder).Decode(0xc420723b60, 0x83600e0, 0xc420080008, 0x5bf2820, 0xc4201500c0, 0x5bf25e0, 0xc420086008, 0x4058110, 0xc42002ce00)
	/Users/build/go/src/github.com/keybase/client/go/client/chat_api_decoder.go:64 +0x166
github.com/keybase/client/go/client.(*CmdChatAPI).Run(0xc42030a500, 0x0, 0x0)
	/Users/build/go/src/github.com/keybase/client/go/client/cmd_chat_api.go:100 +0x1ca
main.mainInner(0xc4201d8600, 0x0, 0x0)
	/Users/build/go/src/github.com/keybase/client/go/keybase/main.go:162 +0x72d
main.main()
	/Users/build/go/src/github.com/keybase/client/go/keybase/main.go:67 +0xa3
```

**Comment by maxtaco** [comment]
Thanks for the report. Cc: @patrickxb

**Comment by patrickxb** [comment]
@antiochp could you send me an example of the JSON you used with `keybase chat api`?  You can redact any of the content, I just want to see the general command and options you used.

Thanks!

**Comment by antiochp** [comment]
Both of these blow up - 

```
keybase chat api -m '{"method": "read", "params": {"options": {"channel": {"name": "<me>,<other>"}}}}'

keybase chat api -m '{"method": "read", "params": {"options": {"channel": {"name": "<other>"}}}}'
```

**Comment by patrickxb** [comment]
How large is the message that you sent that you think is causing this problem?

**Comment by antiochp** [comment]
I think it was about 2048 bytes (don't ask why...).

**Comment by antiochp** [comment]
With hindsight it would probably have made more sense to upload an attachment...
