### ISSUE TITLE
Errors on install

### ISSUE THREAD

**Issue by Miladiir** [keybase/keybase-issues#3081]
On first start of the application on a fresh installation of macOS Sierra, I get the following errors:
There was an error installing updater, service, kbfs.

Additionally, this is what I get when I run the Keybase binary within the app bundle. `/Users/miladiir/Library/Application Support/Keybase/Keybase`is a symlink onto itself, as are the Singleton* files. 

```
Last login: Tue Oct 10 11:13:06 on ttys001
~/ > /Applications/Keybase.app/Contents/MacOS/Keybase ; exit;
Error loading state: { Error: /Users/miladiir/Library/Application Support/Keybase/installer.json: ENOENT: no such file or directory, open '/Users/miladiir/Library/Application Support/Keybase/installer.json'
    at Object.fs.openSync (fs.js:584:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Object.fs.readFileSync (fs.js:491:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:505:29)
    at Object.readFileSync (/Applications/Keybase.app/Contents/Resources/app/desktop/dist/main.bundle.js:6:313055)
    at m.s (/Applications/Keybase.app/Contents/Resources/app/desktop/dist/main.bundle.js:6:312196)
    at m (/Applications/Keybase.app/Contents/Resources/app/desktop/dist/main.bundle.js:6:307748)
    at Object.defineProperty.value (/Applications/Keybase.app/Contents/Resources/app/desktop/dist/main.bundle.js:6:307783)
    at t (/Applications/Keybase.app/Contents/Resources/app/desktop/dist/main.bundle.js:1:256)
    at Object.defineProperty.value (/Applications/Keybase.app/Contents/Resources/app/desktop/dist/main.bundle.js:6:88423)
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/miladiir/Library/Application Support/Keybase/installer.json' }
Using logFd =  19
log: Tue Oct 10 2017 11:16:56 GMT+0200 (CEST) (1507627016423): Version: 1.0.33-20171003193446+d9ceb86ac
error: Tue Oct 10 2017 11:16:56 GMT+0200 (CEST) (1507627016426): (node:2556) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'listenOnConnect' of undefined
error: Tue Oct 10 2017 11:16:56 GMT+0200 (CEST) (1507627016426): (node:2556) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
log: Tue Oct 10 2017 11:16:56 GMT+0200 (CEST) (1507627016713): No app state
log: Tue Oct 10 2017 11:16:56 GMT+0200 (CEST) (1507627016714): Setting open at login
log: Tue Oct 10 2017 11:16:56 GMT+0200 (CEST) (1507627016792): Opened at login: false
log: Tue Oct 10 2017 11:16:56 GMT+0200 (CEST) (1507627016792): Is restore: false
log: Tue Oct 10 2017 11:16:56 GMT+0200 (CEST) (1507627016792): Open hidden: false
log: Tue Oct 10 2017 11:16:56 GMT+0200 (CEST) (1507627016792): Hide main window: false
log: Tue Oct 10 2017 11:16:56 GMT+0200 (CEST) (1507627016802): Hide dock icon: false
From Keybase: log: Tue Oct 10 2017 11:16:57 GMT+0200 (CEST) (1507627017652): Transport using /Users/miladiir/Library/Group Containers/keybase/Library/Caches/Keybase/keybased.sock
From Keybase: log: Tue Oct 10 2017 11:16:57 GMT+0200 (CEST) (1507627017852): RPC [W] localhost: Error: connect ENOENT /Users/miladiir/Library/Group Containers/keybase/Library/Caches/Keybase/keybased.sock
From Keybase: log: Tue Oct 10 2017 11:16:57 GMT+0200 (CEST) (1507627017853): Error in connecting to transport rpc: {"code":"ENOENT","errno":"ENOENT","syscall":"connect","address":"/Users/miladiir/Library/Group Containers/keybase/Library/Caches/Keybase/keybased.sock"}
From Keybase: log: Tue Oct 10 2017 11:16:57 GMT+0200 (CEST) (1507627017854): RPC [I] localhost: connecting (attempt 1)
From Keybase: log: Tue Oct 10 2017 11:16:57 GMT+0200 (CEST) (1507627017879): RPC [W] localhost: Error: connect ENOENT /Users/miladiir/Library/Group Containers/keybase/Library/Caches/Keybase/keybased.sock
From Keybase: log: Tue Oct 10 2017 11:16:58 GMT+0200 (CEST) (1507627018263): Transport using /Users/miladiir/Library/Group Containers/keybase/Library/Caches/Keybase/keybased.sock
From Keybase: log: Tue Oct 10 2017 11:16:58 GMT+0200 (CEST) (1507627018282): ["Dispatching action: notifications:listenForNotifications: ","{\"type\":\"notifications:listenForNotifications\"}"]
From Keybase: log: Tue Oct 10 2017 11:16:58 GMT+0200 (CEST) (1507627018282): PLL: 1
log: Tue Oct 10 2017 11:16:58 GMT+0200 (CEST) (1507627018282): Executing: /Applications/Keybase.app/Contents/SharedSupport/bin/keybase --debug install-auto --format=json --timeout=30s
From Keybase: log: Tue Oct 10 2017 11:16:58 GMT+0200 (CEST) (1507627018290): ["Dispatching action: tracker:registerIdentifyUi: ","{\"type\":\"tracker:registerIdentifyUi\"}"]
From Keybase: log: Tue Oct 10 2017 11:16:58 GMT+0200 (CEST) (1507627018290): PLL: 2
From Keybase: log: Tue Oct 10 2017 11:16:58 GMT+0200 (CEST) (1507627018290): ["Dispatching action: dev:updateDebugConfig: ","{\"type\":\"dev:updateDebugConfig\"}"]
From Keybase: log: Tue Oct 10 2017 11:16:58 GMT+0200 (CEST) (1507627018290): PLL: 3
From Keybase: log: Tue Oct 10 2017 11:16:58 GMT+0200 (CEST) (1507627018304): ["Dispatching action: pinentry:registerPinentryListener: ","{\"type\":\"pinentry:registerPinentryListener\"}"]
From Keybase: log: Tue Oct 10 2017 11:16:58 GMT+0200 (CEST) (1507627018304): PLL: 4
From Keybase: log: Tue Oct 10 2017 11:16:58 GMT+0200 (CEST) (1507627018307): ["Dispatching action: notifications:registerRekeyListener: ","{\"type\":\"notifications:registerRekeyListener\"}"]
From Keybase: log: Tue Oct 10 2017 11:16:58 GMT+0200 (CEST) (1507627018307): PLL: 5
From Keybase: log: Tue Oct 10 2017 11:16:58 GMT+0200 (CEST) (1507627018377): RPC [W] localhost: Error: connect ENOENT /Users/miladiir/Library/Group Containers/keybase/Library/Caches/Keybase/keybased.sock
From Keybase: log: Tue Oct 10 2017 11:16:58 GMT+0200 (CEST) (1507627018378): Error in connecting to transport rpc: {"code":"ENOENT","errno":"ENOENT","syscall":"connect","address":"/Users/miladiir/Library/Group Containers/keybase/Library/Caches/Keybase/keybased.sock"}
From Keybase: log: Tue Oct 10 2017 11:16:58 GMT+0200 (CEST) (1507627018379): RPC [I] localhost: connecting (attempt 1)
From Keybase: log: Tue Oct 10 2017 11:16:58 GMT+0200 (CEST) (1507627018410): RPC [W] localhost: Error: connect ENOENT /Users/miladiir/Library/Group Containers/keybase/Library/Caches/Keybase/keybased.sock
log: Tue Oct 10 2017 11:16:58 GMT+0200 (CEST) (1507627018503): Exec (stdout): {
  "componentResults": [
    {
      "name": "cli",
      "status": {
        "code": 0,
        "name": "OK",
        "desc": "OK",
        "fields": null
      },
      "exitCode": 0
    },
    {
      "name": "updater",
      "status": {
        "code": 1804,
        "name": "ERROR",
        "desc": "open /Users/miladiir/Library/LaunchAgents/keybase.updater.plist.W3D4ZTUX4VTNKLMAVHS3H5OZKAFIRP3K: permission denied",
        "fields": null
      },
      "exitCode": 0
    },
    {
      "name": "service",
      "status": {
        "code": 1804,
        "name": "ERROR",
        "desc": "open /Users/miladiir/Library/LaunchAgents/keybase.service.plist.7EPVR6USP4OUO77XNPGYCKPHNB6YTLBB: permission denied",
        "fields": null
      },
      "exitCode": 0
    },
    {
      "name": "kbfs",
      "status": {
        "code": 1804,
        "name": "ERROR",
        "desc": "open /Users/miladiir/Library/LaunchAgents/keybase.kbfs.plist.4USHLLXFLGVMZQYMFQFYWPVYU3BF6AKQ: permission denied",
        "fields": null
      },
      "exitCode": 0
    },
    {
      "name": "kbnm",
      "status": {
        "code": 0,
        "name": "OK",
        "desc": "OK",
        "fields": null
      },
      "exitCode": 0
    }
  ],
  "status": {
    "code": 1804,
    "name": "ERROR",
    "desc": "open /Users/miladiir/Library/LaunchAgents/keybase.updater.plist.W3D4ZTUX4VTNKLMAVHS3H5OZKAFIRP3K: permission denied (updater). open /Users/miladiir/Library/LaunchAgents/keybase.service.plist.7EPVR6USP4OUO77XNPGYCKPHNB6YTLBB: permission denied (service). open /Users/miladiir/Library/LaunchAgents/keybase.kbfs.plist.4USHLLXFLGVMZQYMFQFYWPVYU3BF6AKQ: permission denied (kbfs)",
    "fields": null
  },
  "fatal": false
}

log: Tue Oct 10 2017 11:16:58 GMT+0200 (CEST) (1507627018503): Exec (stderr): 2017-10-10T11:16:58.363659+02:00 ▶ [DEBU keybase globals.go:410] 001 Created Identify2Cache, max age: 5m0s
2017-10-10T11:16:58.364150+02:00 ▶ [DEBU keybase globals.go:413] 002 Created LinkCache, max size: 65536, clean dur: 1m0s
2017-10-10T11:16:58.364291+02:00 ▶ [DEBU keybase globals.go:415] 003 Created CardCache, max age: 5m0s
2017-10-10T11:16:58.364318+02:00 ▶ [DEBU keybase globals.go:417] 004 made a new full self cache
2017-10-10T11:16:58.364390+02:00 ▶ [DEBU keybase globals.go:419] 005 made a new cached UPAK loader (timeout=10m0s)
2017-10-10T11:16:58.366398+02:00 ▶ [DEBU keybase ui.go:580] 006 Can't set GPG_TTY; discover failed
2017-10-10T11:16:58.366530+02:00 ▶ [DEBU keybase globals.go:393] 007 Keybase CLI 1.0.33-20171003193446+d9ceb86ac
2017-10-10T11:16:58.366563+02:00 ▶ [DEBU keybase globals.go:393] 008 - Built with go1.9
2017-10-10T11:16:58.366574+02:00 ▶ [DEBU keybase globals.go:393] 009 - Visit https://keybase.io for more details
2017-10-10T11:16:58.368260+02:00 ▶ [DEBU keybase main.go:180] 00a + configureProcesses
2017-10-10T11:16:58.368389+02:00 ▶ [DEBU keybase main.go:291] 00b + configureLogging
2017-10-10T11:16:58.368436+02:00 ▶ [DEBU keybase main.go:300] 00c Disabling log forwarding
2017-10-10T11:16:58.368468+02:00 ▶ [DEBU keybase main.go:293] 00d - configureLogging
2017-10-10T11:16:58.368497+02:00 ▶ [DEBU keybase main.go:182] 00e - configureProcesses -> <nil>
2017-10-10T11:16:58.368640+02:00 ▶ [DEBU keybase install_darwin.go:427] 00f Installing components: [cli updater service kbfs kbnm]
2017-10-10T11:16:58.369086+02:00 ▶ [INFO keybase install_darwin.go:524] 010 Checking /usr/local/bin/keybase (/Applications/Keybase.app/Contents/SharedSupport/bin/keybase)
2017-10-10T11:16:58.369495+02:00 ▶ [DEBU keybase install_darwin.go:1094] 011 Using updater path: /Applications/Keybase.app/Contents/SharedSupport/bin/updater
2017-10-10T11:16:58.375255+02:00 ▶ [DEBU keybase launchd.go:141] 012 Output (launchctl remove): 
2017-10-10T11:16:58.375347+02:00 ▶ [DEBU keybase launchd.go:146] 013 Nothing to stop (keybase.updater)
2017-10-10T11:16:58.375368+02:00 ▶ [DEBU keybase install_darwin.go:1104] 014 Installing updater service (keybase.updater, timeout=30s)
2017-10-10T11:16:58.375520+02:00 ▶ [INFO keybase launchd.go:270] 015 Saving /Users/miladiir/Library/LaunchAgents/keybase.updater.plist
2017-10-10T11:16:58.375653+02:00 ▶ [DEBU keybase util.go:183] 016 + SafeWriteToFile("/Users/miladiir/Library/LaunchAgents/keybase.updater.plist")
2017-10-10T11:16:58.375823+02:00 ▶ [DEBU keybase util.go:188] 017 - SafeWriteToFile("/Users/miladiir/Library/LaunchAgents/keybase.updater.plist") -> ok
2017-10-10T11:16:58.375848+02:00 ▶ [ERRO keybase standard.go:232] 018 Error installing updater service: open /Users/miladiir/Library/LaunchAgents/keybase.updater.plist.W3D4ZTUX4VTNKLMAVHS3H5OZKAFIRP3K: permission denied
2017-10-10T11:16:58.375883+02:00 ▶ [ERRO keybase standard.go:232] 019 Error installing updater: open /Users/miladiir/Library/LaunchAgents/keybase.updater.plist.W3D4ZTUX4VTNKLMAVHS3H5OZKAFIRP3K: permission denied
2017-10-10T11:16:58.375954+02:00 ▶ [DEBU keybase install_darwin.go:581] 01a Using binPath: /Applications/Keybase.app/Contents/SharedSupport/bin/keybase
2017-10-10T11:16:58.380312+02:00 ▶ [DEBU keybase launchd.go:141] 01b Output (launchctl remove): 
2017-10-10T11:16:58.380373+02:00 ▶ [DEBU keybase launchd.go:146] 01c Nothing to stop (keybase.service)
2017-10-10T11:16:58.384268+02:00 ▶ [DEBU keybase launchd.go:141] 01d Output (launchctl remove): 
2017-10-10T11:16:58.384330+02:00 ▶ [DEBU keybase launchd.go:146] 01e Nothing to stop (homebrew.mxcl.keybase)
2017-10-10T11:16:58.384358+02:00 ▶ [DEBU keybase install_darwin.go:590] 01f Installing service (keybase.service, timeout=30s)
2017-10-10T11:16:58.384445+02:00 ▶ [INFO keybase launchd.go:270] 020 Saving /Users/miladiir/Library/LaunchAgents/keybase.service.plist
2017-10-10T11:16:58.384463+02:00 ▶ [DEBU keybase util.go:183] 021 + SafeWriteToFile("/Users/miladiir/Library/LaunchAgents/keybase.service.plist")
2017-10-10T11:16:58.384577+02:00 ▶ [DEBU keybase util.go:188] 022 - SafeWriteToFile("/Users/miladiir/Library/LaunchAgents/keybase.service.plist") -> ok
2017-10-10T11:16:58.384594+02:00 ▶ [ERRO keybase standard.go:232] 023 Error installing Keybase service: open /Users/miladiir/Library/LaunchAgents/keybase.service.plist.7EPVR6USP4OUO77XNPGYCKPHNB6YTLBB: permission denied
2017-10-10T11:16:58.384614+02:00 ▶ [ERRO keybase standard.go:232] 024 Error installing service: open /Users/miladiir/Library/LaunchAgents/keybase.service.plist.7EPVR6USP4OUO77XNPGYCKPHNB6YTLBB: permission denied
2017-10-10T11:16:58.388629+02:00 ▶ [DEBU keybase launchd.go:141] 025 Output (launchctl remove): 
2017-10-10T11:16:58.388701+02:00 ▶ [DEBU keybase launchd.go:146] 026 Nothing to stop (keybase.kbfs)
2017-10-10T11:16:58.393486+02:00 ▶ [DEBU keybase launchd.go:141] 027 Output (launchctl remove): 
2017-10-10T11:16:58.393557+02:00 ▶ [DEBU keybase launchd.go:146] 028 Nothing to stop (homebrew.mxcl.kbfs)
2017-10-10T11:16:58.393576+02:00 ▶ [DEBU keybase install_darwin.go:628] 029 Installing KBFS (keybase.kbfs, timeout=30s)
2017-10-10T11:16:58.393679+02:00 ▶ [INFO keybase launchd.go:270] 02a Saving /Users/miladiir/Library/LaunchAgents/keybase.kbfs.plist
2017-10-10T11:16:58.393696+02:00 ▶ [DEBU keybase util.go:183] 02b + SafeWriteToFile("/Users/miladiir/Library/LaunchAgents/keybase.kbfs.plist")
2017-10-10T11:16:58.393831+02:00 ▶ [DEBU keybase util.go:188] 02c - SafeWriteToFile("/Users/miladiir/Library/LaunchAgents/keybase.kbfs.plist") -> ok
2017-10-10T11:16:58.393855+02:00 ▶ [ERRO keybase standard.go:232] 02d Error installing KBFS: open /Users/miladiir/Library/LaunchAgents/keybase.kbfs.plist.4USHLLXFLGVMZQYMFQFYWPVYU3BF6AKQ: permission denied
2017-10-10T11:16:58.393949+02:00 ▶ [INFO keybase install_darwin.go:645] 02e Installing KBNM NativeMessaging whitelists for binary: /Applications/Keybase.app/Contents/SharedSupport/bin/kbnm
2017-10-10T11:16:58.395823+02:00 ▶ [DEBU keybase out_of_date.go:14] 02f + PrintOutOfDateWarnings
2017-10-10T11:16:58.395929+02:00 ▶ [DEBU keybase util.go:455] 030 + GetSocket
2017-10-10T11:16:58.396020+02:00 ▶ [DEBU keybase util.go:456] 031 - GetSocket -> ok
2017-10-10T11:16:58.396073+02:00 ▶ [DEBU keybase socket.go:74] 032 | empty socket wrapper; need a new one
2017-10-10T11:16:58.396162+02:00 ▶ [DEBU keybase socket_nix.go:104] 033 Dialing unix:/Users/miladiir/Library/Group Containers/keybase/Library/Caches/Keybase/keybased.sock
2017-10-10T11:16:58.396844+02:00 ▶ [DEBU keybase socket_nix.go:104] 034 Dialing unix:/Users/miladiir/Library/Caches/Keybase/keybased.sock
2017-10-10T11:16:58.397007+02:00 ▶ [DEBU keybase socket.go:89] 035 | DialSocket -> ERROR: There were multiple errors: dial unix /Users/miladiir/Library/Group Containers/keybase/Library/Caches/Keybase/keybased.sock: connect: no such file or directory; dial unix /Users/miladiir/Library/Caches/Keybase/keybased.sock: connect: no such file or directory
2017-10-10T11:16:58.397033+02:00 ▶ [DEBU keybase out_of_date.go:19] 036 Ignoring error in printOutOfDateWarnings: There were multiple errors: dial unix /Users/miladiir/Library/Group Containers/keybase/Library/Caches/Keybase/keybased.sock: connect: no such file or directory; dial unix /Users/miladiir/Library/Caches/Keybase/keybased.sock: connect: no such file or directory
2017-10-10T11:16:58.397065+02:00 ▶ [DEBU keybase out_of_date.go:20] 037 - PrintOutOfDateWarnings
2017-10-10T11:16:58.497307+02:00 ▶ [DEBU keybase globals.go:497] 038 Calling shutdown first time through
2017-10-10T11:16:58.497479+02:00 ▶ [DEBU keybase login_state.go:1103] 039 + Account "LoginState - Shutdown"
2017-10-10T11:16:58.497547+02:00 ▶ [DEBU keybase login_state.go:950] 03a + acctHandle sending: acctReq LoginState - Shutdown [zLJ55NuJ]
2017-10-10T11:16:58.497577+02:00 ▶ [DEBU keybase login_state.go:953] 03b * acctHandle sent: acctReq LoginState - Shutdown [zLJ55NuJ] (77.131µs)
2017-10-10T11:16:58.497629+02:00 ▶ [DEBU keybase login_state.go:1005] 03c * LoginState running account request: acctReq LoginState - Shutdown [zLJ55NuJ]
2017-10-10T11:16:58.497739+02:00 ▶ [DEBU keybase login_state.go:1008] 03d * LoginState account request complete: acctReq LoginState - Shutdown [zLJ55NuJ]
2017-10-10T11:16:58.497833+02:00 ▶ [DEBU keybase login_state.go:988] 03f - LoginState: shutdown chan closed, exiting requests loop
2017-10-10T11:16:58.497876+02:00 ▶ [DEBU keybase login_state.go:989] 040 - LoginState: Leaving request loop
2017-10-10T11:16:58.497759+02:00 ▶ [DEBU keybase login_state.go:968] 03e - acctHandle done: acctReq LoginState - Shutdown [zLJ55NuJ] (417.338µs)
2017-10-10T11:16:58.497983+02:00 ▶ [DEBU keybase login_state.go:1105] 041 - Account "LoginState - Shutdown"
2017-10-10T11:16:58.498111+02:00 ▶ [DEBU keybase globals.go:556] 042 exiting shutdown code=0; err=<nil>

From Keybase: log: Tue Oct 10 2017 11:16:58 GMT+0200 (CEST) (1507627018572): ["Dispatching action: app:changedFocus: ","{\"type\":\"app:changedFocus\"}"]
From Keybase: log: Tue Oct 10 2017 11:16:58 GMT+0200 (CEST) (1507627018572): PLL: 6
From Keybase: log: Tue Oct 10 2017 11:16:58 GMT+0200 (CEST) (1507627018883): RPC [I] localhost: connecting (attempt 2)
From Keybase: log: Tue Oct 10 2017 11:16:58 GMT+0200 (CEST) (1507627018884): RPC [W] localhost: Error: connect ENOENT /Users/miladiir/Library/Group Containers/keybase/Library/Caches/Keybase/keybased.sock
From Keybase: log: Tue Oct 10 2017 11:16:59 GMT+0200 (CEST) (1507627019414): RPC [I] localhost: connecting (attempt 2)
From Keybase: log: Tue Oct 10 2017 11:16:59 GMT+0200 (CEST) (1507627019415): RPC [W] localhost: Error: connect ENOENT /Users/miladiir/Library/Group Containers/keybase/Library/Caches/Keybase/keybased.sock
From Keybase: log: Tue Oct 10 2017 11:16:59 GMT+0200 (CEST) (1507627019889): RPC [I] localhost: connecting (attempt 3)
From Keybase: log: Tue Oct 10 2017 11:16:59 GMT+0200 (CEST) (1507627019889): RPC [W] localhost: Error: connect ENOENT /Users/miladiir/Library/Group Containers/keybase/Library/Caches/Keybase/keybased.sock
From Keybase: log: Tue Oct 10 2017 11:17:00 GMT+0200 (CEST) (1507627020420): RPC [I] localhost: connecting (attempt 3)
From Keybase: log: Tue Oct 10 2017 11:17:00 GMT+0200 (CEST) (1507627020421): RPC [W] localhost: Error: connect ENOENT /Users/miladiir/Library/Group Containers/keybase/Library/Caches/Keybase/keybased.sock
From Keybase: log: Tue Oct 10 2017 11:17:00 GMT+0200 (CEST) (1507627020891): RPC [I] localhost: connecting (attempt 4)
From Keybase: log: Tue Oct 10 2017 11:17:00 GMT+0200 (CEST) (1507627020891): RPC [W] localhost: Error: connect ENOENT /Users/miladiir/Library/Group Containers/keybase/Library/Caches/Keybase/keybased.sock
From Keybase: log: Tue Oct 10 2017 11:17:01 GMT+0200 (CEST) (1507627021427): RPC [I] localhost: connecting (attempt 4)
From Keybase: log: Tue Oct 10 2017 11:17:01 GMT+0200 (CEST) (1507627021429): RPC [W] localhost: Error: connect ENOENT /Users/miladiir/Library/Group Containers/keybase/Library/Caches/Keybase/keybased.sock
From Keybase: log: Tue Oct 10 2017 11:17:01 GMT+0200 (CEST) (1507627021898): RPC [I] localhost: connecting (attempt 5)
From Keybase: log: Tue Oct 10 2017 11:17:01 GMT+0200 (CEST) (1507627021898): RPC [W] localhost: Error: connect ENOENT /Users/miladiir/Library/Group Containers/keybase/Library/Caches/Keybase/keybased.sock
From Keybase: log: Tue Oct 10 2017 11:17:02 GMT+0200 (CEST) (1507627022432): RPC [I] localhost: connecting (attempt 5)
From Keybase: log: Tue Oct 10 2017 11:17:02 GMT+0200 (CEST) (1507627022433): RPC [W] localhost: Error: connect ENOENT /Users/miladiir/Library/Group Containers/keybase/Library/Caches/Keybase/keybased.sock
From Keybase: log: Tue Oct 10 2017 11:17:02 GMT+0200 (CEST) (1507627022901): RPC [I] localhost: connecting (attempt 6)
From Keybase: log: Tue Oct 10 2017 11:17:02 GMT+0200 (CEST) (1507627022901): RPC [W] localhost: Error: connect ENOENT /Users/miladiir/Library/Group Containers/keybase/Library/Caches/Keybase/keybased.sock
From Keybase: log: Tue Oct 10 2017 11:17:03 GMT+0200 (CEST) (1507627023438): RPC [I] localhost: connecting (attempt 6)
From Keybase: log: Tue Oct 10 2017 11:17:03 GMT+0200 (CEST) (1507627023439): RPC [W] localhost: Error: connect ENOENT /Users/miladiir/Library/Group Containers/keybase/Library/Caches/Keybase/keybased.sock
From Keybase: log: Tue Oct 10 2017 11:17:03 GMT+0200 (CEST) (1507627023904): RPC [I] localhost: connecting (attempt 7)
From Keybase: log: Tue Oct 10 2017 11:17:03 GMT+0200 (CEST) (1507627023904): RPC [W] localhost: Error: connect ENOENT /Users/miladiir/Library/Group Containers/keybase/Library/Caches/Keybase/keybased.sock
log: Tue Oct 10 2017 11:17:03 GMT+0200 (CEST) (1507627023973): Quit the app
From Keybase: log: Tue Oct 10 2017 11:17:03 GMT+0200 (CEST) (1507627023994): ["Dispatching action: app:changedFocus: ","{\"type\":\"app:changedFocus\"}"]
From Keybase: log: Tue Oct 10 2017 11:17:03 GMT+0200 (CEST) (1507627023995): PLL: 7
log: Tue Oct 10 2017 11:17:03 GMT+0200 (CEST) (1507627023995): Executing: /Applications/Keybase.app/Contents/SharedSupport/bin/keybase ctl stop --exclude=app
From Keybase: log: Tue Oct 10 2017 11:17:04 GMT+0200 (CEST) (1507627024440): RPC [I] localhost: connecting (attempt 7)
From Keybase: log: Tue Oct 10 2017 11:17:04 GMT+0200 (CEST) (1507627024440): RPC [W] localhost: Error: connect ENOENT /Users/miladiir/Library/Group Containers/keybase/Library/Caches/Keybase/keybased.sock
log: Tue Oct 10 2017 11:17:04 GMT+0200 (CEST) (1507627024460): Exec (stderr): 2017-10-10T11:17:04.040538+02:00 ▶ [INFO keybase install_darwin.go:761] 001 Uninstall mount: /keybase

log: Tue Oct 10 2017 11:17:04 GMT+0200 (CEST) (1507627024460): Done with ctlsto
```

Deleting the app bundle and folders in `~/Library`titled Keybase has no effect.

**Comment by Miladiir** [comment]
I fixed it. My ~/Library folder was owned by staff:staff and not by me at all. Since the Application does not elevate rights (nor should it ever need to) it was not able to write into ~/Library/LaunchAgents. So maybe test if the folder is. writable and spew out a sensible error message? I don't know if thats really needed though, since the error above also contains the permission denied message.

**Comment by maxtaco** [comment]
Thanks for the very helpful report. Do you by any chance use LastPass?  We've heard it breaks permissions in some cases.  If not, any ideas as to which other software on your system might have done so?  Anything that needs to escalate privileges on install, I guess.

cc: @cjb and @chrisnojima

**Comment by Miladiir** [comment]
I restored my user directory from a backup with [https://www.arqbackup.com](Arq). That was probably it.

**Comment by maxtaco** [comment]
Cool, thanks for closing the loop. I guess we need to fix our installer so that by default it doesn't elevate privileges, but it will in the case of some other app that messed the privileges up that needs to be fixed.
