### ISSUE TITLE
Unable to delete account

### ISSUE THREAD

**Issue by commoner1945** [keybase/keybase-issues#3177]
In Keybase version `1.0.40-20180127033950+76a4b90c9`, click **Setting** > **Delete Me** > **Delete my account forever** > **Yes permanent delete it** throws following error, and can't delete account at all. 

`GENERIC: ERROR CODE 218 - AccountDelete is a devel-only RPC in method keybase.1.login.accountDelete at o.t (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:392353) at o (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:392659) at a (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:392021) at t.convertToError (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:392219) at _rpcClient.invoke.t (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:331023) at file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:795119 at e.t.Deferrals.e._call (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:623532) at file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:623683 at s (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:623312) at e.t.Deferrals.e._fulfill (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:623642)`

**Comment by maxtaco** [comment]
thanks for the report

cc @keybase/react-hackers 

the website should work to delete accounts too...

**Comment by neosiae** [comment]
Doesn't work on the website, either. I've got the following error: "Error In Deletion: DB error".
