### ISSUE TITLE
Error running GUI from command line: ~.config/Keybase/installer.json: ENOENT

### ISSUE THREAD

**Issue by nealmcb** [keybase/keybase-issues#3217]
As a greybeard, I use the command line to launch programs on my Linux machine (Ubuntu).
When I run "keybase" I get the cool pure-command-line interface. Yay!

But sometimes I want to see the GUI.  I didn't see any way to get the GUI window from the command line, but I did notice that `/opt/keybase/Keybase` was running after I found and started Keybase from my KDE prompt.  So I tried just running that (which is not in my $PATH) from the command line, but I get this error:

```
$ /opt/keybase/Keybase                                                                              
Error loading state: { Error: /home/neal/.config/Keybase/installer.json: ENOENT: no such file or directory, open '/home/neal/.config/Keybase/installer.json'
    at Object.fs.openSync (fs.js:584:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Object.fs.readFileSync (fs.js:491:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:505:29)
    at Object.readFileSync (/opt/keybase/resources/app/desktop/dist/main.bundle.js:1:545461)
    at p.default.promptedForCLI.t.default (/opt/keybase/resources/app/desktop/dist/main.bundle.js:1:544612)
    at p.default.promptedForCLI (/opt/keybase/resources/app/desktop/dist/main.bundle.js:1:432240)
    at Object.defineProperty.value (/opt/keybase/resources/app/desktop/dist/main.bundle.js:1:432236)
    at t (/opt/keybase/resources/app/desktop/dist/main.bundle.js:1:256)
    at Object.defineProperty.value (/opt/keybase/resources/app/desktop/dist/main.bundle.js:1:330445)
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/neal/.config/Keybase/installer.json' }
Only one instance of keybase GUI allowed, bailing!
```
So how do I launch the GUI from the command line?

Note - it works fine when launched with my mouse from KDE.  I'm running keybase version 1.0.45-20180321163509+89c9a0ef3a

**Comment by maxtaco** [comment]
Cc @keybase/react-hackers

**Comment by chrisnojima** [comment]
that error message can be ignored.  the real problem is where it says `Only one instance of keybase GUI allowed, bailing!` . That means you already have the gui running somewhere. Maybe in your tray?

**Comment by nealmcb** [comment]
OK, I guess I pased in the output from a subsequent run that seemed like the same error.  Here is the original traceback. (And, of course, avoiding tracebacks in general would also help avoid confusion):

I guess `Error:  Error: No keybase bin path` is the operative (and still mysterious) issue now.

```
sn ~$ /opt/keybase/Keybase                                                                                               [1154/9428]
Error loading state: { Error: /home/neal/.config/Keybase/installer.json: ENOENT: no such file or directory, open '/home/neal/.config
/Keybase/installer.json'
    at Object.fs.openSync (fs.js:584:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Object.fs.readFileSync (fs.js:491:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:505:29)
    at Object.readFileSync (/opt/keybase/resources/app/desktop/dist/main.bundle.js:1:545461)
    at p.default.promptedForCLI.t.default (/opt/keybase/resources/app/desktop/dist/main.bundle.js:1:544612)
    at p.default.promptedForCLI (/opt/keybase/resources/app/desktop/dist/main.bundle.js:1:432240)
    at Object.defineProperty.value (/opt/keybase/resources/app/desktop/dist/main.bundle.js:1:432236)
    at t (/opt/keybase/resources/app/desktop/dist/main.bundle.js:1:256)
    at Object.defineProperty.value (/opt/keybase/resources/app/desktop/dist/main.bundle.js:1:330445)
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/neal/.config/Keybase/installer.json' }
Version: 1.0.45-20180321163509+89c9a0ef3a
Check bounds: { height: 600, width: 800, x: 102, y: 172 } { x: 0, y: 0, width: 1920, height: 1080 } { x: 0, y: 0, width: 1920, heigh
t: 1080 }
Setting login item due to user pref
Opened at login: false
Is restore: false
Open hidden: false
Hide main window: false
Login item settings changed! now true
Hide dock icon: false
Login item settings changed! now true
Error:  Error: No keybase bin path
    at t.default.e (/opt/keybase/resources/app/desktop/dist/main.bundle.js:1:432448)
    at EventEmitter.p.ipcMain.on (/opt/keybase/resources/app/desktop/dist/main.bundle.js:1:331840)
    at emitOne (events.js:96:13)
    at EventEmitter.emit (events.js:191:7)
    at WebContents.<anonymous> (/opt/keybase/resources/electron.asar/browser/api/web-contents.js:247:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:194:7)

Login item settings changed! now true
```

At that point in time I think I only had something I thought was a daemon running. I wish I understood what it was up to also:

`/usr/bin/keybase --debug --log-file /home/neal/.cache/keybase/keybase.service.log service --chdir /run/user/1000/keybase --auto-forked`

**Comment by chrisnojima** [comment]
@oconnor663 thoughts

**Comment by oconnor663** [comment]
The command you're looking for is `run_keybase`. That'll launch the background daemon, the GUI, and the KBFS FUSE mount.

**Comment by oconnor663** [comment]
I think all the errors you're seeing the the GUI's output are expected. Most people never really run the GUI by hand, so the logs aren't very human friendly.

**Comment by oconnor663** [comment]
Woops, clicked the wrong button.

**Comment by nealmcb** [comment]
Excellent - thank you @oconnor663 - just what I was looking for, though I note that it also kills the existing processes, so I guess you wouldn't want to do this if you were in the middle of something.

I looked at everything *starting* with `keybase`, but not things that didn't start with that.

See e.g. https://keybase.io/docs/the_app/install_linux
> To restart Keybase after an update, type run_keybase. This will kill and restart everything, including the KBFS fuse mount.

I guess this can indeed be closed.

**Comment by oconnor663** [comment]
Yes it's more of a restart command than a start command. If you're on a systemd system, and you want to do a pure start without killing anything that's already running, you can try `systemctl --user start keybase kbfs keybase.gui`. That won't start the `/keybase` redirector if it's not already running, but it covers most of what you usually see.
