### ISSUE TITLE
BAD_MERKLE_ROOT: ERROR CODE 232 - invalid team member merkle ordering in method

### ISSUE THREAD

**Issue by kenorb** [keybase/keybase-issues#3230]
I've got the following error when adding a user to the team on macOS:

> `BAD_MERKLE_ROOT: ERROR CODE 232 - invalid team member merkle ordering in method keybase.1.teams.teamAddMember at o.t (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:1:392177) at o (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:1:392483) at a (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:1:391845) at t.convertToError (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:1:392043) at _rpcClient.invoke.t (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:1:349202) at file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:1:1012401 at e.t.Deferrals.e._call (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:1:663274) at file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:1:663425 at s (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:1:663054) at e.t.Deferrals.e._fulfill (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:1:663384)`

----

`Version 1.0.47-20180410052738+f705a9510f (1.0.47-20180410052738+f705a9510f)`

**Comment by maxtaco** [comment]
Thanks for the report, we'll look into it.

**Comment by maxtaco** [comment]
Seems like your device is out of space. That's causing weird failures, I think....

**Comment by maxtaco** [comment]
Once you've cleaned out some space, try `keybase db nuke` and reattempt whatever failed.

**Comment by maxtaco** [comment]
Glad it worked. We should fix that error propagation though...
