### ISSUE TITLE
Everything is broken.

### ISSUE THREAD

**Issue by ChildishGiant** [keybase/keybase-issues#3246]
![image](https://user-images.githubusercontent.com/13716824/40937714-71baefbe-6837-11e8-8309-8dd33fdad41c.png)

EOF from server from the app
`EofError at B.t.Dispatch.n._dispatch_reset (file:///C:/Users/Ali/AppData/Local/Keybase/Gui/resources/app/desktop/dist/index.bundle.js:1:654285) at e.close (file:///C:/Users/Ali/AppData/Local/Keybase/Gui/resources/app/desktop/dist/index.bundle.js:1:656355) at B.t.Transport.n._close (file:///C:/Users/Ali/AppData/Local/Keybase/Gui/resources/app/desktop/dist/index.bundle.js:1:659885) at B.t.Transport.n.reset (file:///C:/Users/Ali/AppData/Local/Keybase/Gui/resources/app/desktop/dist/index.bundle.js:1:659356) at file:///C:/Users/Ali/AppData/Local/Keybase/Gui/resources/app/desktop/dist/index.bundle.js:1:11716 at A.M.reset (file:///C:/Users/Ali/AppData/Local/Keybase/Gui/resources/app/desktop/dist/index.bundle.js:1:11724) at setTimeout (file:///C:/Users/Ali/AppData/Local/Keybase/Gui/resources/app/desktop/dist/index.bundle.js:1:2692656)`

**Comment by ChildishGiant** [comment]
I can visit https://keybase.io/ but https://keybase.io/childishgiant and other user's pages aren't working

**Comment by ChildishGiant** [comment]
Seems to be fixed now
