### ISSUE TITLE
Cannot upload files

### ISSUE THREAD

**Issue by beakface** [keybase/keybase-issues#3265]
Windows user here. I was previously able to upload files to keybase to share with someone.  I have not done so for maybe 3 months, but I've been using chat on keybase without incident in the meantime.

Today I tried uploading files the same way that had worked previously, no go.  I cannot use the WIndows gui to move files over into the keybase window. I tried installing the new "Dokan library bundle" (version 1.1.0.2000) that was suggested in the files section, but the upload file and upload folder options both do nothing after install.  Nothing happens and there is no error message.  I rebooted my machine again, same issue.

I tried doing the keybase log send and it responded with - ERROR not confirmed, even though I believe I confirmed it.

**Comment by beakface** [comment]
Yes, I'm talking about dragging and dropping files.  I'm quite sure I was able to do that previously, though I suppose that could have been only through chat and not in the files section?

I was also not able to use the +New Upload a file or Upload a folder, from the keybase window.  Nothing would happen when I clicked on those. No error message, no reaction at all, as though I hadn't done anything.  I tried again a few minutes ago and suddenly I was able to see and select files to upload.  I hadn't changed anything, rebooted, etc.!!

**Comment by strib** [comment]
Ah, yeah that was probably in chat - we just adding file uploading in the GUI in the release last week.

cc: @jzila @songgao on GUI uploads not working on Windows.

@beakface what about your K: drive?

**Comment by beakface** [comment]
Once the +New Upload folder was working (I'd still love to know why it started responding to my clicks without me changing anything or rebooting), yes it brought up KBFS on my k drive.  I can drag and drop my files from elsewhere onto that drive and see them in the files section of keybase.

Thanks for your help!

**Comment by a2** [comment]
Posted this in keybase/client#12987 but I am seeing issues on macOS too

**Comment by pomidor100500** [comment]
Cannot upload files using GUI.  Trying to send logs using feedback in the menu, doesnt work, says 'cant send log'.

ORK_ERROR: ERROR CODE 1601 - API network error: Post https://api-0.core.keybaseapi.com/_/api/1.0/logdump/send.json: net/http: request canceled (Client.Timeout exceeded while awaiting headers) in method keybase.1.config.logSend
Error: ERROR CODE 1601 - API network error: Post https://api-0.core.keybaseapi.com/_/api/1.0/logdump/send.json: net/http: request canceled (Client.Timeout exceeded while awaiting headers) in method keybase.1.config.logSend at new RPCError (file:///C:/Users/Home/AppData/Local/Keybase/Gui/resources/app/desktop/dist/main.bundle.js:1:1034340) at convertToRPCError (file:///C:/Users/Home/AppData/Local/Keybase/Gui/resources/app/desktop/dist/main.bundle.js:1:1035227) at convertToError (file:///C:/Users/Home/AppData/Local/Keybase/Gui/resources/app/desktop/dist/main.bundle.js:1:1035286) at file:///C:/Users/Home/AppData/Local/Keybase/Gui/resources/app/desktop/dist/main.bundle.js:1:2408504 at file:///C:/Users/Home/AppData/Local/Keybase/Gui/resources/app/desktop/dist/vendors~main.bundle.js:2:205168 at Deferrals._call (file:///C:/Users/Home/AppData/Local/Keybase/Gui/resources/app/desktop/dist/vendors~main.bundle.js:2:10925) at file:///C:/Users/Home/AppData/Local/Keybase/Gui/resources/app/desktop/dist/vendors~main.bundle.js:2:11117 at trampoline (file:///C:/Users/Home/AppData/Local/Keybase/Gui/resources/app/desktop/dist/vendors~main.bundle.js:2:10653) at Deferrals._fulfill (file:///C:/Users/Home/AppData/Local/Keybase/Gui/resources/app/desktop/dist/vendors~main.bundle.js:2:11070) at ret (file:///C:/Users/Home/AppData/Local/Keybase/Gui/resources/app/desktop/dist/vendors~main.bundle.js:2:10066)
{ "code": 1601, "fields": null, "desc": "API network error: Post https://api-0.core.keybaseapi.com/_/api/1.0/logdump/send.json: net/http: request canceled (Client.Timeout exceeded while awaiting headers)", "details": "Error code 1601: API_NETWORK_ERROR in method keybase.1.config.logSend" }

**Comment by neoramos** [comment]
Wow... 
On Mac OS I can't upload files.  they just hang after the progress bar starts. 
I can no longer use this tool :( , as I see there has been no activity since 2020.
