### ISSUE TITLE
An exception is thrown for "keybase push" command

### ISSUE THREAD

**Issue by bozydar** [keybase/keybase-issues#3278]
Arch linux:
```
$ keybase push         
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x55cadce1c454]

goroutine 1 [running]:
github.com/keybase/client/go/client.(*UI).OutputWriter(...)
        /build/keybase/src/.gopath/src/github.com/keybase/client/go/client/ui.go:1050
github.com/keybase/client/go/client.(*UI).Println(0x0, 0xc4204c95c8, 0x1, 0x1, 0xc420510128, 0xc4204c9820, 0xe8)
        /build/keybase/src/.gopath/src/github.com/keybase/client/go/client/ui.go:1070 +0x24
github.com/keybase/client/go/client.NewCmdCompatPush.func1(0xc420510120)
        /build/keybase/src/.gopath/src/github.com/keybase/client/go/client/cmd_compat.go:27 +0x6b
github.com/keybase/client/go/vendor/github.com/keybase/cli.Command.Run(0x55cadce844c4, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x55cadcec8e03, ...)
        /build/keybase/src/.gopath/src/github.com/keybase/client/go/vendor/github.com/keybase/cli/command.go:132 +0x503
github.com/keybase/client/go/vendor/github.com/keybase/cli.(*App).Run(0xc420205200, 0xc42000c060, 0x2, 0x2, 0x0, 0x0)
        /build/keybase/src/.gopath/src/github.com/keybase/client/go/vendor/github.com/keybase/cli/app.go:161 +0x4f1
github.com/keybase/client/go/libcmdline.(*CommandLine).Parse(0xc42045c690, 0xc42000c060, 0x2, 0x2, 0xc4204c9e48, 0x4, 0x4, 0x4)
        /build/keybase/src/.gopath/src/github.com/keybase/client/go/libcmdline/cmdline.go:658 +0xc4
main.mainInner(0xc4203ca700, 0x0, 0x0, 0x0, 0x0, 0x0)
        /build/keybase/src/.gopath/src/github.com/keybase/client/go/keybase/main.go:148 +0x3d4
main.main()
        /build/keybase/src/.gopath/src/github.com/keybase/client/go/keybase/main.go:75 +0xb9
```

**Comment by strib** [comment]
Hmm @zapu, is this a vestigal pgp thing?

**Comment by maxtaco** [comment]
we should kill `GlobUI`
