### ISSUE TITLE
Can't delete conversation in app

### ISSUE THREAD

**Issue by FireFart** [keybase/keybase-issues#3351]
In the desktop/mobile app I have an conversation which I can not delete:
![image](https://user-images.githubusercontent.com/105281/53400567-71550200-39ae-11e9-82d7-4eef7608f73b.png)

It says the conversation is waiting for the other user (which I do not know) to open the app and rekey the conversation.

There seems like no option to delete this conversation (or whatever it is).

**Comment by Aaron-Shaw** [comment]
same here

**Comment by FireFart** [comment]
Output from `keybase chat ls` on this conversation:
```
Unable to decrypt chat message (transient): You are not a member of this team (error 2623)
```

**Comment by anowlcalledjosh** [comment]
I'm also encountering this after leaving a team – opening a team chat and pressing "no don't join the team" resulted in this error:

```
Error: ERROR CODE 2623 - You are not a member of this team
in method chat.1.local.getTLFConversationsLocal
at new s (file:///opt/keybase/resources/app/desktop/dist/main.bundle.js:1:561326)
at file:///opt/keybase/resources/app/desktop/dist/main.bundle.js:1:561922
at u (file:///opt/keybase/resources/app/desktop/dist/main.bundle.js:1:561961)
at file:///opt/keybase/resources/app/desktop/dist/main.bundle.js:1:1242674
at file:///opt/keybase/resources/app/desktop/dist/main.bundle.js:1:3018547
at e._call (file:///opt/keybase/resources/app/desktop/dist/main.bundle.js:1:2580383)
at file:///opt/keybase/resources/app/desktop/dist/main.bundle.js:1:2580523
at s (file:///opt/keybase/resources/app/desktop/dist/main.bundle.js:1:2580163)
at e._fulfill (file:///opt/keybase/resources/app/desktop/dist/main.bundle.js:1:2580493)
at s (file:///opt/keybase/resources/app/desktop/dist/main.bundle.js:1:2579694)
```

and there's no button to remove the chat from the list.

Log id: 30ed948e9b4e693d6c50c51c
