### ISSUE TITLE
Website error that leaks uncompiled ToffeeScript from stacktrace

### ISSUE THREAD

**Issue by pizzafox** [keybase/keybase-issues#3602]
I logged in to the Keybase website and was greeted with this error which leaks the uncompiled front-end source code in a big modal it showed the following stacktrace:
```coffeescript
0 ReferenceError: features is not defined
1 [between lines 33 and 34] /vol/data0/home/keybase/src/keybase/keybase/views/user/settings_dropdown.toffee
2 at _TMPL_ (evalmachine.:257:17)
3 at view.run (/vol/data0/home/keybase/src/keybase/keybase/node_modules/toffee/lib/view.js:179:17)
4 at engine.runSync (/vol/data0/home/keybase/src/keybase/keybase/node_modules/toffee/lib/engine.js:191:20)
5 at engine._inlineInclude (/vol/data0/home/keybase/src/keybase/keybase/node_modules/toffee/lib/engine.js:238:19)
6 at engine._inlineInclude (/vol/data0/home/keybase/src/keybase/keybase/node_modules/toffee/lib/engine.js:4:59)
7 at engine._fn_partial (/vol/data0/home/keybase/src/keybase/keybase/node_modules/toffee/lib/engine.js:262:19)
8 at engine._fn_partial (/vol/data0/home/keybase/src/keybase/keybase/node_modules/toffee/lib/engine.js:4:59)
9 at Object.options.partial (/vol/data0/home/keybase/src/keybase/keybase/node_modules/toffee/lib/engine.js:167:28)
10 [between lines 19 and 20] /vol/data0/home/keybase/src/keybase/keybase/views/user/settings_dropdown.toffee
11
31:             <li><a onclick="return false;" href="#_" class="link-add-signed-statement" data-ss_sig_gen="KeybaseUsername"><i class="fas fa-exclamation-triangle"></i> Sign your public key to prove it's yours, or</a></li>
32:             <li><a onclick="return false;" href="#_" class="link-account-reset"><i class="fas fa-exclamation-triangle"></i> Reset your keys</a></li>
33:           :}
34:           if them.get_all_signing_keys()?.length and !them.lockdown?.status and not features.autoreset_pipeline {:
35:             <li><a onclick="return false;" href="#_" class="link-account-reset">Reset your keys &amp; start from scratch</a></li>
```
Here's an image of the page after the error occured:
![funny keybase error](https://user-images.githubusercontent.com/7608555/66605592-34b4d000-eb65-11e9-9173-28ff408a8512.png)

**Comment by malgorithms** [comment]
thanks, this should be fixed. There was a timing issue with a deploy, and there was a couple minute span where this was possible. 

We let these render stack traces get printed, even in production, on purpose.
