### ISSUE TITLE
Cant upload files, cant send report

### ISSUE THREAD

**Issue by pomidor100500** [keybase/keybase-issues#3882]
Cannot upload files using GUI. Trying to send logs using feedback in the menu, doesnt work, says 'cant send log'.

ORK_ERROR: ERROR CODE 1601 - API network error: Post https://api-0.core.keybaseapi.com/_/api/1.0/logdump/send.json: net/http: request canceled (Client.Timeout exceeded while awaiting headers) in method keybase.1.config.logSend
Error: ERROR CODE 1601 - API network error: Post https://api-0.core.keybaseapi.com/_/api/1.0/logdump/send.json: net/http: request canceled (Client.Timeout exceeded while awaiting headers) in method keybase.1.config.logSend at new RPCError (file:///C:/Users/Home/AppData/Local/Keybase/Gui/resources/app/desktop/dist/main.bundle.js:1:1034340) at convertToRPCError (file:///C:/Users/Home/AppData/Local/Keybase/Gui/resources/app/desktop/dist/main.bundle.js:1:1035227) at convertToError (file:///C:/Users/Home/AppData/Local/Keybase/Gui/resources/app/desktop/dist/main.bundle.js:1:1035286) at file:///C:/Users/Home/AppData/Local/Keybase/Gui/resources/app/desktop/dist/main.bundle.js:1:2408504 at file:///C:/Users/Home/AppData/Local/Keybase/Gui/resources/app/desktop/dist/vendorsmain.bundle.js:2:205168 at Deferrals._call (file:///C:/Users/Home/AppData/Local/Keybase/Gui/resources/app/desktop/dist/vendorsmain.bundle.js:2:10925) at file:///C:/Users/Home/AppData/Local/Keybase/Gui/resources/app/desktop/dist/vendorsmain.bundle.js:2:11117 at trampoline (file:///C:/Users/Home/AppData/Local/Keybase/Gui/resources/app/desktop/dist/vendorsmain.bundle.js:2:10653) at Deferrals._fulfill (file:///C:/Users/Home/AppData/Local/Keybase/Gui/resources/app/desktop/dist/vendorsmain.bundle.js:2:11070) at ret (file:///C:/Users/Home/AppData/Local/Keybase/Gui/resources/app/desktop/dist/vendorsmain.bundle.js:2:10066)
{ "code": 1601, "fields": null, "desc": "API network error: Post https://api-0.core.keybaseapi.com/_/api/1.0/logdump/send.json: net/http: request canceled (Client.Timeout exceeded while awaiting headers)", "details": "Error code 1601: API_NETWORK_ERROR in method keybase.1.config.logSend" }

**Comment by strib** [comment]
We will have a hotfix release out soon to fix this on Windows.
