### ISSUE TITLE
App Loading for ever 

### ISSUE THREAD

**Issue by rgangaderan** [keybase/keybase-issues#4087]
I am trying to install Keybase on my M1 Pro chip, 
I am getting a log to send page and the command is not working in the terminal.
I also tried with brew install, still the same 

Error: Failure while executing; `/Applications/Keybase.app/Contents/SharedSupport/bin/keybase install-auto` exited with 2. Here's the output:
2021-12-06T13:10:53.508892+01:00 ▶ [INFO keybase install_darwin.go:669] 001 Checking /usr/local/bin/keybase (/Applications/Keybase.app/Contents/SharedSupport/bin/keybase)
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x5643e53]

goroutine 1 [running]:
github.com/keybase/client/go/install.installCommandLineForBinPath(0xc0000405c0, 0x3c, 0xc000042320, 0x16, 0x1, 0xe222e88, 0xc000156bc0, 0x0, 0xc0004ae000)
	/Users/build/go/src/github.com/keybase/client/go/install/install_darwin.go:707 +0x93
github.com/keybase/client/go/install.installCommandLine(0x6b09000, 0xc00012f080, 0x0, 0x0, 0x1, 0xe222e88, 0xc000156bc0, 0x1f, 0x203000)
	/Users/build/go/src/github.com/keybase/client/go/install/install_darwin.go:670 +0x1e4
github.com/keybase/client/go/install.Install(0x6b09000, 0xc00012f080, 0x0, 0x0, 0x0, 0x0, 0xc00004c0f0, 0x5, 0x5, 0x1, ...)
	/Users/build/go/src/github.com/keybase/client/go/install/install_darwin.go:491 +0x320b
github.com/keybase/client/go/install.InstallAuto(0x6b09000, 0xc00012f080, 0x0, 0x0, 0x0, 0x0, 0x28fa6ae00, 0xe222e88, 0xc000156bc0, 0x0, ...)
	/Users/build/go/src/github.com/keybase/client/go/install/install_darwin.go:442 +0x291
github.com/keybase/client/go/client.(*cmdInstallAuto).Run(0xc000280b80, 0xc0002aa000, 0x7fbd930)
	/Users/build/go/src/github.com/keybase/client/go/client/cmd_install_osx.go:360 +0x114
main.mainInner(0xc00012f080, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/build/go/src/github.com/keybase/client/go/keybase/main.go:248 +0x847
main.main()
	/Users/build/go/src/github.com/keybase/client/go/keybase/main.go:71 +0x91

![image](https://user-images.githubusercontent.com/36160986/144864280-c18a2ee2-d31d-409a-8fbc-2bef5e8dab44.png)

I want to know whether Keybase support for new Macbook Pro with M1 Pro chip or is that anything I need to do

**Comment by rgangaderan** [comment]
@
